window.animes = [  { 
    name: "Spy x Family", 
    poster: "https://m.media-amazon.com/images/I/81DrxABCeNL._AC_UF894,1000_QL80_.jpg", 
    alt: "Spy x Family Poster",
    genre: "Action • Comedy", 
    season: "⏳ 3",
    episodes: "▶️ 50",
    studio: "WIT Studio x CloverWorks",
    rating: "⭐ 5",
    mood: "Wholesome", 
    story: "Season 1: Master spy 'Twilight' creates a fake family with an assassin and a telepath to infiltrate an elite school and preserve world peace. Season 2: The Forgers navigate high-stakes danger during the Cruise Adventure arc, testing Yor's resolve as an assassin while the family's bonds deepen. Season 3: The stakes escalate as Loid’s tragic past is finally revealed through the 'Reminiscence' arc, while Anya faces her toughest challenges at Eden Academy to secure the final Stella Stars needed for Operation Strix.",
    hook: "A master spy, a deadly assassin, and a telepathic child play house to save the world.",
    quote: "For the sake of the mission, and for a better world where children don't have to cry.",
    watch: "https://aniwatchtv.to/watch/spy-x-family-17977?ep=89506",
    trailer: "https://www.youtube.com/embed/JP6vBnazpWI?si=OH9rmN6oZcCbbUVU",
    laugh: "https://www.youtube.com/watch?v=-QOPZSAUn7s",
    spotify: "https://open.spotify.com/embed/album/7e4jxoNaSmYXIWq7qQfQ0r?utm_source=generator",
    keywords: "Espionage, assassin, telepath, forger, secrets, mission, family, wholesome, comedy, operation, academy, peace, disguise, identities, telepathy, thriller, parenting, school, bond, peanuts, action, friendship, lies, trust, domestic, intrigue, war, elite, gadgets, elegant, cold-war, strix, yor, loid, anya, bondman, ostania, westalis, berlint, eden, undercover, marriage, childcare, cooking, poisons, silencer, sniper, pistols, coding, intelligence, diplomacy, counter-intelligence, garden, thorn-princess, twilight, penguin, ouchies, stella-star, tonitrus-bolt, henderson, sewing, secret-police, internal-affairs, briar, yuri, franky, informant, shopkeeper, nightfall, fiona, tennis, and yacht-party.",
    keyGenre: "Action, Comedy, Shonen, Slice of Life, Spy, Espionage, Family Dynamics, Found Family, Secret Identity, Parenting, School Life, Undercover, Tactical, Historical Fiction, Thriller, Satire, Wholesome, Life Lessons",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Frieren",
    poster: "https://m.media-amazon.com/images/I/712af18VpML._AC_UF894,1000_QL80_.jpg", 
    alt: "Frieren Poster",
    genre: "Adventure • Fantasy", 
    season: "⏳ 1",
    episodes: "▶️ 28",
    studio: "Madhouse",
    rating: "⭐ 5", 
    mood: "Melancholic", 
    story: "Decades after the Hero's party defeated the Demon King, the immortal elf mage Frieren watches her former comrades pass away one by one. Realizing how fleeting human life is compared to her own, she embarks on a new quest to the land of souls. Along the way, she retraces her old steps, takes on a young apprentice, and seeks to understand the true meaning of the connections she once took for granted.",
    hook: "An immortal elf mage learns the value of human connection long after the quest is over.",
    quote: "I realized I knew nothing about the humans I traveled with.",
    watch: "https://aniwatchtv.to/watch/frieren-beyond-journeys-end-18542?ep=107257",
    trailer: "https://www.youtube.com/embed/Iwr1aLEDpe4?si=NVAT1zVHrW0DU3UO",
    laugh: "https://www.youtube.com/watch?v=nEw4b2c6j6Y",
    spotify: "https://open.spotify.com/embed/album/4fgJZhpksYeOUtddVplxWS?utm_source=generator",
    keywords: "Elf, mage, immortality, legacy, journey, time, friendship, party, hero, demons, magic, melancholy, growth, memories, spellcasting, adventure, slow-paced, atmospheric, fantasy, exploration, history, passing, life, death, nostalgia, wisdom, apprenticeship, grimoires, staff, wand, peaceful, himmel, fern, stark, zoltraak, aureole, goddesses, demons, reflection, eternity, blue-moon-weed, soul, funeral, mourning, hundred-years, artifacts, mana-concealment, flamme, qual, sages-of-destruction, aura, scales, mimic, treasure-chest, village, statues, flowers, winter, ritual, exams, first-class-mage, serie, loden, dragon, warrior, priest, heiter, eisen, gratitude, footsteps, sky, and silence.",
    keyGenre: "Adventure, Fantasy, Shonen, Seinen, Slice of Life, Philosophical, High Fantasy, Life Lessons, Journey, Magic System, Melancholy, Atmospheric, Nostalgia, Coming of Age, Historical, Legacy, Peace, Quiet Growth",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Solo Leveling",
    poster: "https://m.media-amazon.com/images/I/811qwtjnRKL._AC_UF894,1000_QL80_.jpg", 
    alt: "Solo Leveling Poster",
    genre: "Action • Fantasy", 
    season: "⏳ 2",
    episodes: "▶️ 12",
    studio: "A-1 Pictures",
    rating: "⭐ 5", 
    mood: "Hype", 
    story: "Season 1: In a world where hunters clear dungeons to protect humanity, Sung Jin-woo is known as the world's weakest hunter. After a near-death experience in a mysterious double dungeon, he is chosen by a 'System' that allows him to level up through quests. He begins a grueling journey to transform from a weakling into a powerful warrior. Season 2: Having reached new heights of power, Jin-woo faces even more formidable threats as the gates continue to open. He must delve deeper into the secrets of the System and his own awakening, leading to a clash that will determine the fate of the hunter world.",
    hook: "The world's weakest hunter survives a hidden trial to become the ultimate player.",
    quote: "The System used me, and now I will use the System. Arise.",
    watch: "https://aniwatchtv.to/watch/solo-leveling-18718?ep=114721",
    trailer: "https://www.youtube.com/embed/bssSj4cKsrI?si=Ob-9MqOwtc-h0vqm",
    laugh: "https://www.youtube.com/watch?v=XLeDEPK1cAc",
    spotify: "https://open.spotify.com/embed/playlist/1vOIkDgeiJiSvyc9o34lOv?utm_source=generator",
    keywords: "Hunter, dungeons, leveling, system, shadows, monarch, power, growth, gates, monsters, raids, dungeon, necromancy, action, progression, zero-to-hero, soldiers, swords, daggers, quests, ranks, survival, training, evolution, intense, gaming, mechanics, boss, battles, dark, sung-jinwoo, arise, s-rank, shadows, igris, beru, kaisel, void, double-dungeon, strength, e-rank, crystals, mana, essence, player, penalty, daily-quest, hidden-class, necromancer, armor, speed, agility, health-points, awakening, re-awakening, association, chairman, korea, jeju-island, ant-king, blue-venom-fanged-kasaka, orcs, knights, demon-tower, architect, chalice, heart, ashborn, fragments, ruler, and sovereign.",
    keyGenre: "Action, Fantasy, Shonen, Overpowered, Leveling, RPG Mechanics, Dungeon Crawl, Progression Fantasy, Survival, Urban Fantasy, Dark Fantasy, Zero to Hero, Necromancy, Monster Hunter, Thriller, Supernatural, Martial Arts",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Reincarnation of the Strongest Exorcist in Another World", 
    poster: "https://m.media-amazon.com/images/M/MV5BNDZjNTgyNDktZTJmZi00YzQ3LWJjNGMtOWQ0ODE1OGMwNmMzXkEyXkFqcGc@._V1_.jpg", 
    alt: "Strongest Exorcist Poster",
    genre: "Fantasy • Isekai", 
    season: "⏳ 1",
    episodes: "▶️ 13",
    studio: "Studio Blanc",
    rating: "⭐ 3", 
    mood: "Tactical", 
    story: "After being betrayed and killed by his own disciples, Haruyoshi, the world's strongest exorcist, uses a secret reincarnation spell to start anew. Reborn as Seika Lamprogue in a world of magic, he discovers he lacks mana, which is the local source of power. However, he soon realizes that his ancient yin-yang arts and spirit-summoning abilities are far superior to the sorcery of this new world, allowing him to navigate noble politics and academy life with ease.",
    hook: "A betrayed master of spirits is reborn in a world of magic where he lacks mana but rules the occult.",
    quote: "I don't need magic. These 'insignificant' arts from my previous life are more than enough to crush you.",
    watch: "https://aniwatchtv.to/watch/the-reincarnation-of-the-strongest-exorcist-in-another-world-18290?ep=97035",
    trailer: "https://www.youtube.com/embed/TGEOMXmcra0?si=IYWoNiIwPVhOHwen",
    laugh: "https://www.youtube.com/watch?v=Eq9p0kgZDYE",
    spotify: "https://open.spotify.com/embed/album/1n09nDMHZn16o46Dd7t3V0?utm_source=generator",
    keywords: "Exorcist, reincarnation, magic, spirits, betrayal, overpowered, isekai, cunning, strategy, talismans, demons, academy, noble, monsters, spirits, past-life, skills, hidden-power, fantasy, adventure, revenge, yin-yang, elements, tactical, spells, summoning, monsters, luck, intelligence, destiny, haruyoshi, seika, shikigami, amyu, lamprogue, dragons, manipulation, curse, amulets, ritual, fire-magic, water-magic, wind-magic, earth-magic, spiritual-energy, paper-craft, illusions, kitsune, disguise, tournament, prophecy, destiny, family-politics, resentment, wisdom, reincarnation-circle, esoteric, occult, sealing, monsters, dark-arts, shadow-manipulation, fox-spirit, and ancient-japan.",
    keyGenre: "Isekai, Fantasy, Action, Shonen, Reincarnation, Supernatural, Overpowered, School Life, Magic System, Strategy, Occult, Exorcism, Mythology, Tactical, Betrayal, Noble Society, Spirits, Academy, Revenge",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Mushoku Tensei",
    poster: "https://a.storyblok.com/f/178900/1064x1596/fb327f6af0/mushoku-tensei-season-2-key-visual.png/m/filters:quality(95)format(webp)", 
    alt: "Mushoku Tensei Poster",
    genre: "Adventure • Drama", 
    season: "⏳ 2",
    episodes: "▶️ 48",
    studio: "Studio Bind",
    rating: "⭐ 5", 
    mood: "Reflective", 
    story: "Season 1: A 34-year-old shut-in is reborn as Rudeus Greyrat in a world of swords and sorcery. Retaining his adult memories, he masters magic from a young age and sets out to live his new life to the fullest. However, a massive magical disaster teleports him and his student to a distant continent, forcing them on a long journey home. Season 2: After the trials of his journey, Rudeus enters the Ranoa Academy of Magic to investigate the disaster that changed his life. As he navigates academy life and reunites with familiar faces, he must overcome personal trauma and prepare for the larger destiny that awaits him.",
    hook: "A shut-in gets a second chance at life in a world of magic, vowing to live without regrets.",
    quote: "In this world, I will give it my all. I will live my life so that I have no regrets when I die again.",
    watch: "https://aniwatchtv.to/watch/mushoku-tensei-jobless-reincarnation-15820?ep=51229",
    trailer: "https://www.youtube.com/embed/k5VxfJpzy1Q?si=9SrAIuNDsV24Aq9R",
    laugh: "https://www.youtube.com/shorts/oIc8IIsXysY",
    spotify: "https://open.spotify.com/embed/playlist/616C0594Uhg2FGhDWdlKe7?utm_source=generator",
    keywords: "Isekai, redemption, magic, life, growth, family, tragedy, world-building, journey, wizard, reincarnation, drama, fantasy, romance, training, adventure, survival, lore, destiny, mana, exploration, skills, characters, depth, transformation, travel, continents, gods, demons, struggle, rudeus, eris, roxy, sylphiette, ghislaine, paul, fittoa, teleportation, mana-calamity, hitogami, chantless-casting, tutoring, languages, beast-people, sword-god-style, water-god-style, north-god-style, demon-eye, foresight, staff, robe, demon-continent, superd, ruijerd, migurdia, zenith, lilia, norn, aisha, dragon-god, orsted, reincarnation-sorcery, life-cycles, mistakes, regret, adulthood, and world-map.",
    keyGenre: "Isekai, Adventure, Fantasy, Seinen, Drama, Reincarnation, Coming of Age, World Building, Magic System, High Fantasy, Life Lessons, Redemption, Philosophical, Journey, Romance, Survival, Tragedy, Lore",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Mashle",
    poster: "https://wallpapercg.com/media/ts_orig/20968.webp", 
    alt: "Mashle Poster",
    genre: "Comedy • Fantasy", 
    season: "⏳ 2",
    episodes: "▶️ 24",
    studio: "A-1 Pictures",
    rating: "⭐ 5", 
    mood: "Hilarious", 
    story: "Season 1: In a world where your social status is determined by your magical ability, Mash Burnedead is a rare individual born without mana. To protect his peaceful life with his adoptive father, he enrolls in the prestigious Easton Magic Academy. Lacking magic, Mash uses his incredible physical strength to 'muscle' his way through magical challenges. Season 2: As Mash gains recognition, he faces the Divine Visionary Selection Exam, where the academy's elite compete for the highest honor. However, a dark organization known as Innocent Zero begins to move in the shadows, threatening the peace of the magical world and forcing Mash to prove that muscles can truly conquer any spell.",
    hook: "In a world where magic is everything, one boy uses raw physical power to crush the elite.",
    quote: "If I can't use magic, I'll just have to crush your spells with my bare hands.",
    watch: "https://aniwatchtv.to/watch/mashle-magic-and-muscles-18339?ep=100069",
    trailer: "https://www.youtube.com/embed/_ce5_P1Hj5A?si=DuLSeLJuKKPBDsoD",
    laugh: "https://www.youtube.com/watch?v=9pdVpqPyFu8",
    spotify: "https://open.spotify.com/embed/playlist/6YO8wCQJBISVRivbCnbMMq?utm_source=generator",
    keywords: "Muscles, magic, school, comedy, parody, cream-puffs, strength, weights, wizardry, satire, action, academy, spells, social-status, power, fitness, humor, magic-less, underdog, brawl, gym, friendship, competition, divine-visionary, sticks, robes, broomsticks, stone, physical-prowess, mash, burneaded, lance, dot, finn, lemon, innocent-zero, wand, lines, burp, bench-press, protein, dumbbells, squats, iron, fist, punch, non-magical, marks, face-lines, adler, lang, orca, dormitories, coins, gold-coins, silver-coins, duels, magic-police, regro, wahlberg, cell-war, graviole, explosions, biceps, triceps, and deadlift.",
    keyGenre: "Comedy, Fantasy, Action, Shonen, Parody, Satire, Gag, Slapstick, Underdog, Overpowered, School Life, Magic Academy, Martial Arts, Fitness, Supernatural, Battle, Social Satire, Absurdist Humor",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Aristocrat's Otherworldly Adventure", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuRy2h4jCWsG_fM4h4RGGHH7rWneifFTnhlw&s", 
    alt: "Aristocrat's Adventure Poster",
    genre: "Action • Fantasy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Magic Bus",
    rating: "⭐ 2", 
    mood: "Lighthearted", 
    story: "Kazuya Shiina dies protecting a young girl and is reincarnated as Cain von Silford, the third son of a noble family. During his baptism, he receives the blessings of seven gods, which grant him stats and magical abilities that are ridiculously overpowered. Cain tries to hide his world-breaking power to live a normal life, but his noble duties and the constant threats to the kingdom keep dragging him into high-stakes adventures.",
    hook: "Reborn with the excessive blessings of seven gods, a young noble tries to hide his world-breaking power.",
    quote: "The gods were a little too generous... How am I supposed to live a normal life with these stats?",
    watch: "https://aniwatchtv.to/watch/the-aristocrats-otherworldly-adventure-serving-gods-who-go-too-far-18355?ep=99947",
    trailer: "https://www.youtube.com/embed/Ozq63sr8ONI?si=2fyvDtGK9iWsDMFP",
    laugh: "https://www.youtube.com/watch?v=XC9ZnqeLyos",
    spotify: "https://open.spotify.com/embed/playlist/1rJbCSQpbVIbuRtw5QIVb9?utm_source=generator",
    keywords: "Noble, god-blessed, overpowered, isekai, reincarnation, child-prodigy, magic, status, leveling, fantasy, adventure, kingdom, protection, skills, divine, blessing, monsters, training, social, nobility, castle, stats, growth, spells, combat, exploration, swords, lighthearted, cain, silford, gods, esfort, teltier, silk, reine, guilds, baptism, cheat-skills, creation-magic, appraisal, inventory, storage, dragon-slayer, barony, viscount, count, king, princess, engagement, academy, summoning, mythical-beasts, holy-magic, dark-magic, swordsmanship, rank-up, rewards, mansions, tea-parties, and god-tier.",
    keyGenre: "Isekai, Fantasy, Action, Shonen, Reincarnation, Overpowered, Noble Society, Kingdom Building, High Society, School Life, Magic System, Adventure, Leveling, Divine Blessing, Comedy, Slice of Life",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Misfit of Demon King Academy", 
    poster: "https://i.ebayimg.com/images/g/TIYAAOSwpAVnPqUb/s-l1200.jpg", 
    alt: "Misfit of Demon King Academy Poster",
    genre: "Fantasy • School", 
    season: "⏳ 2",
    episodes: "▶️ 37",
    studio: "SILVER LINK.",
    rating: "⭐ 4", 
    mood: "Arrogant", 
    story: "Season 1: Anos Voldigoad, the Demon King of Tyranny, reincarnates after 2,000 years into a peaceful era. He enrolls in the Demon King Academy, only to find that his descendants are weak and his legacy has been rewritten to favor a false Demon King. Anos must reclaim his throne while exposing the truth behind the corrupted history. Season 2: Following the resolution of the conflict between humans and demons, Anos faces new threats from the gods and the 'Spirit King.' As he delves into the secrets of the mythological age, he must protect his friends and ensure that the peace he sacrificed everything for is not destroyed by ancient conspiracies.",
    hook: "The legendary Demon King reincarnates after 2,000 years only to find his legacy has been erased.",
    quote: "Did you think that killing me would be enough to make me die?",
    watch: "https://aniwatchtv.to/watch/the-misfit-of-demon-king-academy-1768?ep=22722",
    trailer: "https://www.youtube.com/embed/rBBtzhYH0CA?si=Rj45xRR2Js6zzDRn",
    laugh: "https://www.youtube.com/watch?v=Meees5CUb-A",
    spotify: "https://open.spotify.com/embed/playlist/70yEnyxuXXwkKSe460xtoS?utm_source=generator",
    keywords: "Demon-king, reincarnation, academy, overpowered, lineage, magic, arrogance, school, battle, legacy, destiny, defiance, history, spells, combat, rivalry, monsters, castle, authority, strength, myths, legends, bloodline, conflict, truth, memories, swords, magic-circles, gods, absolute-power, anos, voldigoad, misha, sasha, dilhade, tyrannies, reincarnation, swords, founding-ancestor, venuzdonoar, seven-elder-demon-emperors, kanon, jerga, human-realm, spirits, fan-union, songs, destruction, creation, origin-magic, time-manipulation, heartbeats, flicking, castle-throwing, throne, silver-sea, bubbles, layers, and gods-of-order.",
    keyGenre: "Fantasy, Action, Shonen, Overpowered, School Life, Reincarnation, Demon Lord, Supernatural, Magic System, Academy, Mythology, Battle, High Society, Legend, Historical Fantasy, Comedy, Arrogant Protagonist",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Greatest Demon Lord Is Reborn as a Typical Nobody", 
    poster: "https://i.pinimg.com/736x/94/ee/a1/94eea1d8308d9559fd9de13bcbb39eea.jpg", 
    alt: "Greatest Demon Lord Poster",
    genre: "Fantasy • Magic", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "SILVER LINK.",
    rating: "⭐ 3", 
    mood: "Lonely", 
    story: "The ancient Demon Lord Varvatos, tired of being lonely due to his absolute power, reincarnates as Ard Meteel in a future world. He hopes for a normal life and friends, but he soon finds that the general level of magic has plummeted during his absence. Even his most basic efforts are seen as god-like, making it impossible for him to blend in. As he joins a magic academy, he must deal with old enemies and new challenges that threaten the peaceful life he desires.",
    hook: "A lonely Demon Lord seeks a normal life by reincarnating as a commoner, but he's still too powerful.",
    quote: "I just wanted to make friends. I didn't think I'd still be this much stronger than everyone else.",
    watch: "https://aniwatchtv.to/watch/the-greatest-demon-lord-is-reborn-as-a-typical-nobody-17682?ep=89369",
    trailer: "https://www.youtube.com/embed/CL3Ec5WLeuQ?si=kKDgPVm8kKzLbZEh",
    laugh: "https://www.youtube.com/shorts/17rnKQ3y7WI",
    spotify: "https://open.spotify.com/embed/playlist/0xmuneeeSTLNWGw3sxxeWI?utm_source=generator",
    keywords: "Demon-lord, reincarnation, nobody, school, magic, loneliness, friendship, overpowered, past-life, academy, comedy, action, monsters, spells, adventure, fantasy, girls, destiny, power-gap, secrets, hidden-identity, duel, battle, training, skills, legends, myths, world-order, social-life, history, ard, meteel, irena, ginny, sylphy, varvatos, lydia, ancient, average, reincarnation, magic-circles, high-school, social-anxiety, popularity, past-regrets, demon-army, goddess, future-tech, sword-magic, dragon-clans, hero-party, past-self, time-travel, altered-timeline, and school-festival.",
    keyGenre: "Fantasy, Magic, Action, Shonen, Reincarnation, Overpowered, School Life, Demon Lord, Comedy, Supernatural, Academy, Battle, Past Life, Coming of Age, Secret Identity, Friendship",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Re: Zero",
    poster: "https://preview.redd.it/re-zero-starting-life-in-another-world-season-4-new-key-v0-0wi3zxkael1g1.jpeg?auto=webp&s=77d1fe2aedb47b9d6414b19d928f4e657f16d863", 
    alt: "Re: Zero Poster",
    genre: "Drama • Psychological", 
    season: "⏳ 3",
    episodes: "▶️ 58",
    studio: "White Fox",
    rating: "⭐ 2", 
    mood: "Traumatic", 
    story: "Season 1: Subaru Natsuki is suddenly summoned to a fantasy world where he discovers he has the ability to 'Return by Death.' He must use this traumatic power to save a silver-haired elf named Emilia and his new friends from certain doom. Season 2: Subaru faces the trials of the Sanctuary, a mysterious place that holds the secrets of the Witches of Sin. He must confront his past and forge new alliances to break a cycle of suffering. Season 3: Following the events at the Sanctuary, Subaru and Emilia's camp travel to the water-gate city of Priestella. There, they are drawn into a massive conflict with the Witch's Cult, forcing Subaru to lead a desperate resistance to save the city and its people.",
    hook: "A powerless boy must die repeatedly to rewrite a tragic destiny in a cruel fantasy world.",
    quote: "I will save you. No matter how many times I have to die to do it.",
    watch: "https://aniwatchtv.to/watch/rezero-starting-life-in-another-world-212?ep=4813",
    trailer: "https://www.youtube.com/embed/Slz_rahWp6Y?si=_6HEX5tOzYL6JF82",
    laugh: "https://www.youtube.com/watch?v=cQS-PO-_81E",
    spotify: "https://open.spotify.com/embed/playlist/17mhV25tdeEWamYxP0qFwG?utm_source=generator",
    keywords: "Loop, death, suffering, psychological, isekai, return-by-death, magic, witches, cult, pain, emotion, fantasy, tragedy, mystery, survival, trials, monsters, maids, knights, kingdom, curses, trauma, despair, hope, fate, time-travel, resilience, courage, love, complexity, subaru, emilia, rem, ram, puck, betelgeuse, satella, roswaal, lugnica, sanctuary, whale, sloth, greed, gluttony, envy, pride, wrath, lust, factor, unseen-hand, shadows, tea-party, echidna, rabbits, clones, fortress, spirits, contract, garfiel, frederica, otto, petra, and confession.",
    keyGenre: "Isekai, Psychological, Drama, Fantasy, Seinen, Thriller, Survival, Dark Fantasy, Time Loop, Tragedy, Mystery, Supernatural, Gore, Resilience, Life Lessons, Magical Realism, Romance, Horror",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "I Was Reincarnated As The 7th Prince", 
    poster: "https://m.media-amazon.com/images/M/MV5BM2Y5YjU1ZTYtYjkyOC00MzRmLTgyMWYtNzYxNzY5OWYzYmExXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "7th Prince Poster",
    genre: "Fantasy • Magic", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Tsumugi Akita Animation",
    rating: "⭐ 4", 
    mood: "Obsessive", 
    story: "A commoner mage who spent his life studying magic dies wishing he could have mastered more. He is reborn as Lloyd, the 7th prince of the Saloum Kingdom. With his adult memories and an insatiable curiosity for magic, Lloyd uses his royal resources to perform dangerous experiments and master forbidden spells. Despite his childish appearance, his magical power is unmatched, leading him to accidentally solve major kingdom crises while pursuing his personal research.",
    hook: "A magic-obsessed mage is reborn as a prince and uses his royal status to master forbidden sorcery.",
    quote: "I want to see more magic. There's so much I couldn't reach in my last life.",
    watch: "https://aniwatchtv.to/watch/i-was-reincarnated-as-the-7th-prince-so-i-can-take-my-time-perfecting-my-magical-ability-19132?ep=123156",
    trailer: "https://www.youtube.com/embed/CpZcllLRDnU?si=t_563t75Z-g65Fya",
    laugh: "https://www.youtube.com/shorts/miUOi5AnX40",
    spotify: "https://open.spotify.com/embed/playlist/0TiAzh7tzVzbHgTXQFRxuS?utm_source=generator",
    keywords: "Prince, magic-nerd, reincarnation, research, sorcery, spells, overpowered, obsession, experiment, royal, family, child, genius, elements, circles, mana, monsters, academy, adventure, fantasy, skills, grimoire, summoning, testing, exploration, knowledge, ancient-arts, tactical, battles, curiosity, lloyd, grim, silfa, tao, albert, saloum, grimoires, forbidden-magic, double-casting, mastery, manipulation, blue-flame, vacuum, lightning, alchemy, golems, ancient-civilization, spirits, energy-flow, anatomy, science, testing-limits, lab, library, dungeon-crawling, assassination-arts, and qi.",
    keyGenre: "Fantasy, Magic, Isekai, Shonen, Overpowered, Reincarnation, Research, Scientific Magic, Adventure, Action, Comedy, Royal Society, High Society, Sorcery, Battle, Child Protagonist, Exploration",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Apothecary Diaries",
    poster: "https://m.media-amazon.com/images/M/MV5BNjAxMmFjZjgtYjM1ZS00NzdmLTliZDktZmIyMzU5YTBlNDBmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Apothecary Diaries Poster",
    genre: "Drama • Mystery", 
    season: "⏳ 2",
    episodes: "▶️ 24",
    studio: "TOHO animation STUDIO",
    rating: "⭐ 5", 
    mood: "Intriguing", 
    story: "Season 1: Maomao, a young woman trained in herbal medicine, is kidnapped and sold into the Imperial Palace as a lowly servant. Her knowledge of poisons and medicine allows her to solve a mystery involving the health of the emperor's heirs, catching the eye of the influential eunuch Jinshi. She is soon promoted to a food taster and investigator, navigating the complex politics and scandals of the Inner Court. Season 2: Maomao continues her role as a vital asset to the palace, tackling even more intricate and dangerous mysteries. As her relationship with Jinshi develops and her past is slowly revealed, she must use all her wits to survive the deadly intrigues that threaten the imperial family.",
    hook: "An eccentric herbalist uses her knowledge of poisons to solve deadly mysteries within the Emperor's palace.",
    quote: "It's a matter of dosage. Anything can be a medicine or a poison depending on how you use it.",
    watch: "https://aniwatchtv.to/watch/the-apothecary-diaries-18578?ep=108898",
    trailer: "https://www.youtube.com/embed/XYNGkSvFT8c?si=VuALbWtpMFzPMfmL",
    laugh: "https://www.youtube.com/watch?v=1GgX5_DTaGI",
    spotify: "https://open.spotify.com/embed/album/60GhreuWPvQvllHiuvptsJ?utm_source=generator",
    keywords: "Apothecary, poison, palace, mystery, medicine, court-intrigue, herbalist, detective, concubines, emperor, beauty, logic, science, historical, drama, deduction, secrets, medicine-testing, inner-court, eunuches, scandals, politics, toxins, herbs, survival, intelligence, rumors, investigation, healing, discovery, maomao, jinshi, gyokuyou, lihuwa, gaoshun, forensics, concubines, forbidden-city, cosmetics, lead-poisoning, honey, wood-sorrel, red-light-district, foster-father, verdigris, jars, garden, winter-roses, fireworks, ritual, dancers, eunuchs, and high-consort.",
    keyGenre: "Mystery, Drama, Historical, Seinen, Shoujo, Medical, Forensics, Detective, Analytical, Political Intrigue, High Society, Court Drama, Slice of Life, Science, Psychological, Romance, Life Lessons",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Hero Is Overpowered but Overly Cautious", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHxBhm4XirnvBqLPQzrWxxnDGrQOo_iwSKxw&s", 
    alt: "Overly Cautious Hero Poster",
    genre: "Comedy • Fantasy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "White Fox",
    rating: "⭐ 3", 
    mood: "Frustrating", 
    story: "The goddess Ristarte is tasked with saving a world of extreme difficulty and summons a hero named Seiya Ryuguin. Seiya's stats are incredibly high, but he has a major quirk: he is pathologically cautious. He refuses to enter any battle unless he is completely over-leveled and over-prepared, often spending weeks training and buying hundreds of spare items for a single fight. Despite his frustrating attitude, his methods prove effective against the brutal monsters of the world.",
    hook: "A hero with god-tier stats refuses to fight until he is 1000% prepared for every possible scenario.",
    quote: "Ready perfectly. I won't move an inch until I'm absolutely certain of victory.",
    watch: "https://aniwatchtv.to/watch/cautious-hero-the-hero-is-overpowered-but-overly-cautious-1350?ep=70704",
    trailer: "https://www.youtube.com/embed/kuOmOD2lCPA?si=6j_xS1FiG0W3VyLj",
    laugh: "https://www.youtube.com/watch?v=AJFa0lJSsJs",
    spotify: "https://open.spotify.com/embed/playlist/76Rfi5bdq50xiW2fXyidlF?utm_source=generator",
    keywords: "Caution, hero, training, preparation, comedy, goddess, isekai, stats, monsters, overkill, funny, satire, fantasy, adventure, leveling, power, skills, strategy, caution-levels, armor, inventory, divine, realm, demon-lord, safety, tactical, survival, humor, perfectionist, seiya, rista, gaeburande, gods, valkyrie, adena, training, gym, stats, safety-first, atomic-split-slash, fire-magic, status-check, fake-stats, herbs, synthesized, smoke-bombs, six-pack, muscle-training, divine-swordsmanship, armor-stacking, items, and slime-cautiousness.",
    keyGenre: "Comedy, Fantasy, Isekai, Shonen, Overpowered, Parody, Satire, Strategy, Tactical, Adventure, Survival, RPG Mechanics, Slapstick, Training, Dark Comedy, Supernatural, Magic System",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Water Magician", 
    poster: "https://m.media-amazon.com/images/M/MV5BOGJlZmZmOGYtNWJjNy00ZDI1LThmZGEtYjk3ZmExNzVhMjMwXkEyXkFqcGc@._V1_.jpg", 
    alt: "Water Magician Poster",
    genre: "Fantasy • Adventure", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Seven Arcs",
    rating: "⭐ 4", 
    mood: "Healing", 
    story: "In a world where magic is synonymous with warfare, a young man discovers he has an extraordinary talent for water magic. Eschewing the typical path of a combatant, he chooses to use his powers to improve the lives of the people in his rural village. By developing innovative irrigation systems and healing techniques, he demonstrates that magic's true value lies in creation and preservation rather than destruction.",
    hook: "A gentle mage uses his rare affinity for water to build a peaceful life instead of going to war.",
    quote: "Water can heal anything. It’s the source of all life and the calmest magic there is.",
    watch: "https://aniwatchtv.to/watch/the-water-magician-19770?ep=141570",
    trailer: "https://www.youtube.com/embed/wQwk6ztpoXM?si=g-7JW95-S5KqYK1Q",
    laugh: "https://www.youtube.com/shorts/DZyIRawK-c4",
    spotify: "https://open.spotify.com/embed/playlist/5g7suE3AnQ7XKnpZwuIDJY?utm_source=generator",
    keywords: "Water, magic, relaxing, slice-of-life, fantasy, village, nature, calm, adventure, elements, spells, liquid, hydro, farming, community, everyday-life, magical-world, atmosphere, gentle, peaceful, magic-user, growth, simple-living, exploration, creativity, environment, friendship, water-bending, artisan, cozy, cultivation, irrigation, purity, healing, stream, ocean, lake, meditation, tranquility, garden, flowers, tea, reflection, animals, fish, rain, mist, clouds, seasons, harvest, blue, clear, and ripples.",
    keyGenre: "Fantasy, Slice of Life, Seinen, Relaxing, Iyashikei, Atmospheric, Nature, Peaceful, Magic System, Creative, Simple Life, Community, Farming, Gentle, Life Lessons, Meditation, Rural",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Eminence In Shadow",
    poster: "https://media.animationdigitalnetwork.com/images/show/d0465ad8-4974-4331-bc12-3a8a3a02cb77/affiche.width=630,height=900,quality=80", 
    alt: "Eminence In Shadow Poster",
    genre: "Action • Comedy", 
    season: "⏳ 2",
    episodes: "▶️ 32",
    studio: "Nexus",
    rating: "⭐ 5", 
    mood: "Absurd", 
    story: "Season 1: Cid Kagenou is obsessed with the idea of becoming a 'mastermind in the shadows.' After being reincarnated into a magical world, he creates a fictional secret organization called Shadow Garden to fight an imaginary evil cult. To his surprise, the cult is real, and his subordinates believe he is a tactical genius. Season 2: Cid continues his chuunibyou antics, traveling to the Lawless City and getting involved in a clash between vampire progenitors and other power players. While he treats everything like a game, his overwhelming power and the accidental successes of Shadow Garden continue to reshape the world in the shadows.",
    hook: "A boy obsessed with mastermind tropes accidentally creates a real secret organization and fights a real cult.",
    quote: "I am... Atomic. In the shadows, I lurk and hunt the shadows.",
    watch: "https://aniwatchtv.to/watch/the-eminence-in-shadow-17473?ep=94440",
    trailer: "https://www.youtube.com/embed/Ciy0kf5EE3E?si=3a5MswO1sBwgU4YY",
    laugh: "https://www.youtube.com/watch?v=4_0BzpRA5aU",
    spotify: "https://open.spotify.com/embed/album/1rLZAEZNU3Dj9mq7H9zl9m?utm_source=generator",
    keywords: "Chuunibyou, shadow, garden, organization, mastermind, comedy, parody, overpowered, isekai, secret, identity, action, cool, edge, atomic, magic, cult, misunderstanding, darkness, knights, adventure, sword, style, roleplay, tactical, funny, manipulation, world-domination, heroics, slime, cid, kagenou, alpha, beta, epsilon, delta, shadow-garden, diabolos, mob-character, excalibur, piano, moonlight-sonata, mitsugoshi-company, chocolate, burgers, coins, terrorists, school-attack, sanctuary, aurora, witch-of-calamity, rose, oriara, and garden-of-shadows.",
    keyGenre: "Action, Comedy, Isekai, Shonen, Overpowered, Parody, Satire, Chuunibyou, Secret Identity, Dark Fantasy, Psychological, Mystery, Secret Society, Martial Arts, Tactical, Roleplay, Magic System",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Villainess Level 99", 
    poster: "https://m.media-amazon.com/images/I/81VKA-DwQzL._UF1000,1000_QL80_.jpg", 
    alt: "Villainess Level 99 Poster",
    genre: "Fantasy • Villainess", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Jumondou",
    rating: "⭐ 4", 
    mood: "Awkward", 
    story: "Reborn as Eumiella Dolkness, the hidden boss of an otome game, a young girl decides to spend her entire childhood grinding levels in secret to ensure her survival. By the time she enters the royal academy, she has reached Level 99. Her overwhelming dark magic and anti-social behavior lead the other students and the kingdom's authorities to believe she is the legendary Demon Lord, creating a series of misunderstandings as she tries to navigate a peaceful school life.",
    hook: "A gamer reborn as a villainess hits max level to avoid her fate, only to be mistaken for the Demon Lord.",
    quote: "I just like to grind. I didn't mean to become more powerful than the actual demon lord.",
    watch: "https://aniwatchtv.to/watch/villainess-level-99-i-may-be-the-hidden-boss-but-im-not-the-demon-lord-18829?ep=114847",
    trailer: "https://www.youtube.com/embed/Ojv7vHiIDqg?si=3QL3-Nj3wVFfFKPc",
    laugh: "https://www.youtube.com/shorts/UyqaCDzP-9w",
    spotify: "https://open.spotify.com/embed/album/6d7BoNyOmRDbCEVcLKHmvB?utm_source=generator",
    keywords: "Villainess, leveling, dark-magic, boss, game, stats, academy, misunderstanding, overpowered, isekai, black-hair, antisocial, comedy, fantasy, dungeon, training, shadows, survival, noble, school, level-cap, dragon, hidden, strength, strategy, romance, avoidance, noble-life, skills, grinding, yumiela, dolkness, patrick, dark-attribute, black-magic, dungeon, grind, stats, hidden-boss, flute, eggs, hatching, ryuu, kingdom, light-heroine, Alicia, prince, expulsion, common-sense, social-awkwardness, and heavy-magic.",
    keyGenre: "Isekai, Fantasy, Villainess, Shoujo, Overpowered, Leveling, RPG Mechanics, School Life, Comedy, Magic System, Dark Magic, Social Satire, Reincarnation, Noble Society, Adventure, Strategy",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "I'm in Love with the Villainess", 
    poster: "https://m.media-amazon.com/images/M/MV5BMGMzMjNkYzYtNWZlMS00MDI3LTk1NjMtZDljZmE5OWRhNzMxXkEyXkFqcGc@._V1_.jpg", 
    alt: "In Love with the Villainess Poster",
    genre: "Comedy • Romance", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Platinum Vision",
    rating: "⭐ 3", 
    mood: "Obsessive", 
    story: "Rei Ohashi finds herself reincarnated as the protagonist of her favorite otome game, 'Revolution.' Instead of pursuing the handsome princes, Rei is determined to woo the game's villainess, Claire François, whom she has always adored. Using her meta-knowledge of the game, Rei endures Claire's bullying with joy and works tirelessly to protect her from the tragic fate that awaits her in the game's original story.",
    hook: "A girl reincarnates into a game and skips the princes to pursue the arrogant villainess instead.",
    quote: "I love you, Miss Claire! I'll stay by your side even if the whole world turns against you.",
    watch: "https://aniwatchtv.to/watch/im-in-love-with-the-villainess-18590?ep=107295",
    trailer: "https://www.youtube.com/embed/oHDgq8LrYYk?si=HitVAKm7C7FmIc1a",
    laugh: "https://www.youtube.com/watch?v=RZI3Fpk40eM",
    spotify: "https://open.spotify.com/embed/playlist/2FctJyVcVJ1ex9yEzVoPZl?utm_source=generator",
    keywords: "Villainess, yuri, romance, otome-game, isekai, devotion, comedy, obsession, school, noble, social-class, magic, protagonist, love, comedy, heart-warming, game-world, fan, pride, aristocrat, commoner, dynamics, dating-sim, plot-armor, choice, interaction, bullying, affection, devotion, humor, rae, taylor, claire, francois, revolution, commoner, yuri, romance, bullying, maids, service, chocolate, sweets, teasing, royalty, political-unrest, equality, courage, and flirtation.",
    keyGenre: "Isekai, Yuri, Romance, Comedy, Shoujo, Villainess, Otome, School Life, Social Satire, Political Intrigue, High Society, Slice of Life, LGBTQ+, Parody, Magic System, Reincarnation, Drama",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "7th Time Loop", 
    poster: "https://m.media-amazon.com/images/I/91sHdmMFw6L._UF1000,1000_QL80_.jpg", 
    alt: "7th Time Loop Poster",
    genre: "Romance • Fantasy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Studio Kai",
    rating: "⭐ 4", 
    mood: "Resilient", 
    story: "Rishe Weitzner has a secret: she is on her seventh life. Each of her previous lives ended at the age of twenty after she had mastered a different profession, ranging from a merchant to a knight. In her seventh loop, she is unexpectedly proposed to by Prince Arnold of Galkhein—the very man who killed her in a previous life. Determined to live a long and peaceful life this time, Rishe accepts the proposal and uses all her accumulated skills to navigate the dangerous politics of the palace and change the future.",
    hook: "A woman uses skills from six past lives to survive being married to the prince who killed her.",
    quote: "I will live a long life this time. I’ll use every skill I’ve learned to ensure it.",
    watch: "https://aniwatchtv.to/watch/7th-time-loop-the-villainess-enjoys-a-carefree-life-married-to-her-worst-enemy-18784?ep=114760",
    trailer: "https://www.youtube.com/embed/GFkQZL51UQA?si=Eh7UtU0p9oja1z1m",
    laugh: "https://www.youtube.com/shorts/km8J9FTmnwI",
    spotify: "https://open.spotify.com/embed/album/5GR4pzBheA1kzn8fCtesR7?utm_source=generator",
    keywords: "Loop, reincarnation, noble, survival, skills, time, destiny, romance, marriage, prince, villain, strategy, knowledge, trade, medicine, combat, merchant, knight, life, fate, repetition, choices, growth, past-lives, adventure, political, intrigue, history, future, resilience, rishe, arnold, galkhein, loops, engagement, fate, war, peace, survival-skills, dancing, etiquette, herbalism, jewelry, trade-routes, diplomacy, swordsmanship, maid-disguise, castle, garden, and moon-viewing.",
    keyGenre: "Romance, Fantasy, Shoujo, Drama, Historical, Time Loop, Reincarnation, Political Intrigue, Strategy, Noble Society, High Society, Survival, Medical, Business, Martial Arts, Mystery, Life Lessons",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "I'll Become A Villainess Who Goes Down In History", 
    poster: "https://fr.web.img2.acsta.net/img/61/27/612765b791b31b8fdf0d317486ed731b.jpg", 
    alt: "Villainess History Poster",
    genre: "Fantasy • Drama", 
    season: "⏳ 1",
    episodes: "▶️ 13",
    studio: "MAHO FILM",
    rating: "⭐ 4", 
    mood: "Ambitious", 
    story: "Alicia hates typical goody-two-shoes heroines, so when she is reincarnated as her favorite otome game villainess, she vows to become the greatest villain in history. To achieve this, she trains harder than anyone in magic and swordsmanship and studies complex subjects. However, her efforts to be 'evil' through competence and reform inadvertently win her the respect of the nobility and the commoners alike.",
    hook: "A girl tries her hardest to be a legendary villain, only to accidentally become a beloved prodigy.",
    quote: "I'll be the greatest villain. If I’m going to be bad, I might as well be the best at it.",
    watch: "https://aniwatchtv.to/watch/ill-become-a-villainess-who-goes-down-in-history-19334?ep=128348",
    trailer: "https://www.youtube.com/embed/bKWDjXAJQR0?si=vKzZR61ZOodt6Q56",
    laugh: "https://www.youtube.com/shorts/B6954wtJXVk",
    spotify: "https://open.spotify.com/embed/playlist/53PncXFrx8LxR6fYDnoHWi?utm_source=generator",
    keywords: "Villainess, evil, ambition, reincarnation, history, legacy, noble, child, training, magic, social-status, isekai, otome-game, reputation, smart, cunning, power, status, leadership, influence, destiny, kingdom, manipulation, future, growth, intelligence, defiance, school, society, greatness, alicia, williams, duke, villainy, morality, history, training, noble-education, sword-practice, library, forbidden-books, commoners, village, poverty, reform, and bad-girl.",
    keyGenre: "Isekai, Villainess, Fantasy, Drama, Shoujo, Reincarnation, Strategy, Noble Society, High Society, Political Intrigue, Social Reform, Training, Magic System, Psychological, Ambition, Historical Fantasy",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "I May Be A Guild Receptionist But I'll Solo To Clock Out on Time", 
    poster: "https://m.media-amazon.com/images/M/MV5BMzA3N2U1NDQtYzQyZi00NmY2LWEzZjktMTU2OWFiZWViNzZlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Guild Receptionist Poster",
    genre: "Action • Comedy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "CloverWorks",
    rating: "⭐ 3", 
    mood: "Stressed", 
    story: "Alina just wants a steady desk job so she can leave work at 5 PM sharp. However, when the guild's incompetent adventurers fail to clear dungeons, her paperwork begins to pile up. To solve the problem at the source, she secretly enters the dungeons herself and obliterates high-level bosses in record time, all while maintaining her identity as a simple, tired receptionist.",
    hook: "A tired office worker secretly hunts high-level bosses just so she can finish her paperwork by 5 PM.",
    quote: "I'm leaving at five. If the boss is in the way, I'll just have to crush it myself.",
    watch: "https://aniwatchtv.to/watch/i-may-be-a-guild-receptionist-but-ill-solo-any-boss-to-clock-out-on-time-19441?ep=131718",
    trailer: "https://www.youtube.com/embed/bVrzN-r4MKA?si=3MQ7o6wYUjhgeEir",
    laugh: "https://www.youtube.com/watch?v=eTz3vZPOOsk",
    spotify: "https://open.spotify.com/embed/playlist/6dkXJpINjENNoAelG6AXds?utm_source=generator",
    keywords: "Receptionist, guild, desk-job, overtime, combat, overpowered, secret-strength, monster, hunting, dungeon, adventure, comedy, stress, work-life-balance, efficiency, action, hammer, brute-force, boss, paperwork, fantasy, quests, hidden, skill, training, clocking-out, efficiency, speed, power, funny, alina, clover, jade, work, guild, overtime, stress, monsters, administrative, pink-hair, hammer-strike, executioner, guild-master, paperwork-stack, red-tape, coffee, and vacation.",
    keyGenre: "Action, Comedy, Fantasy, Seinen, Overpowered, Satire, Workplace Drama, Slice of Life, Monster Hunter, Dungeon Crawl, Parody, Corporate Satire, Magic System, Secret Identity, Daily Life",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "KonoSuba", 
    poster: "https://m.media-amazon.com/images/M/MV5BNTQ5NzJjMjgtNDliNC00YTdmLWJiOTQtYWRiMzY4OWU5NGQ3XkEyXkFqcGc@._V1_.jpg", 
    alt: "KonoSuba Poster",
    genre: "Comedy • Adventure", 
    season: "⏳ 3",
    episodes: "▶️ 31",
    studio: "Studio Deen",
    rating: "⭐ 3", 
    mood: "Absurd", 
    story: "Season 1: Kazuma Satou dies an embarrassing death and is offered a chance to reincarnate in a fantasy world. He chooses to bring the goddess Aqua with him as his 'item,' only to realize she's useless. They form a party with a one-shot mage and a masochistic knight. Season 2: The dysfunctional party faces even more absurd threats, from mobile fortresses to cult leaders, while constantly struggling with debt and their own incompetence. Season 3: After their success in the Crimson Demon Village, the group is invited to the royal palace. Kazuma's luck is put to the test as they deal with royal conspiracies and the ever-present threat of the Demon King's generals.",
    hook: "A boy is reincarnated into a world of adventure with a useless goddess and a team of idiots.",
    quote: "Explosion! My life for one single, perfect explosion a day!",
    watch: "https://aniwatchtv.to/watch/konosuba-gods-blessing-on-this-wonderful-world-342?ep=7736",
    trailer: "https://www.youtube.com/embed/N1AO7k2o78g?si=jtaPh76FQQQtyr",
    laugh: "https://www.youtube.com/watch?v=FAyxROvl3tk",
    spotify: "https://open.spotify.com/embed/playlist/1cE4jyK9rUFtWgKlJo8Zr1?utm_source=generator",
    keywords: "Comedy, parody, isekai, useless-goddess, explosion-magic, masochist, knight, shut-in, adventure, fantasy, party, dysfunctional, funny, luck, quest, debt, monsters, laughter, satire, reincarnation, skills, absurd, tavern, quests, guild, world, journey, friendship, greed, irony, kazuma, aqua, megumin, darkness, chomusuke, eris, beldia, crimson-demons, gender-equality, frogs, cabbages, winter-shogun, succubus, axis-cult, hikkikomori, panty-thief, explosion, and debt-collector.",
    keyGenre: "Comedy, Isekai, Adventure, Fantasy, Shonen, Parody, Satire, Slapstick, RPG Mechanics, Magic System, Reincarnation, Supernatural, Absurdist Humor, Slice of Life, Quest, Dysfunctional Family",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The World Finest Assassin", 
    poster: "https://m.media-amazon.com/images/I/817IwMgf87L._UF1000,1000_QL80_.jpg", 
    alt: "Finest Assassin Poster",
    genre: "Action • Isekai", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "SILVER LINK.",
    rating: "⭐ 5", 
    mood: "Calculated", 
    story: "The world's greatest assassin is murdered by the organization he served and is reborn into a world of magic as Lugh Tuatha Dé. A goddess tasks him with one final mission: kill the world's 'Hero' before he destroys the planet. Lugh must use his modern tactical knowledge, chemistry, and new magical gifts to prepare for the ultimate hit while growing up in a noble house of assassins.",
    hook: "A modern-day hitman is reborn as a magical noble to carry out one final hit: killing the world's Hero.",
    quote: "Target acquired. In this life, I’ll kill a hero with the skills of an assassin and the knowledge of a mage.",
    watch: "https://aniwatchtv.to/watch/the-worlds-finest-assassin-gets-reincarnated-in-a-different-world-as-an-aristocrat-17482?ep=83489",
    trailer: "https://www.youtube.com/embed/YI7_wYJQLZU?si=QhFa_v5MqaJMFfLw",
    laugh: "https://www.youtube.com/shorts/fCw7H_jMqsY",
    spotify: "https://open.spotify.com/embed/playlist/37qqtfR1qsultT6aQ4aP24?utm_source=generator",
    keywords: "Assassin, hitman, reincarnation, tactical, calculation, skills, weapons, magic, noble, mission, training, strategy, lethality, gadgets, combat, intelligence, plan, execution, target, shadows, cold, precise, isekai, fantasy, growth, tools, sniping, martial-arts, chemistry, shadows, lugh, tuatha-de, dia, tart, maha, assassination, hero, target, mission, spear-magic, threads, makeup-disguise, merchant-house, loyalty, and goddess-contract.",
    keyGenre: "Isekai, Action, Thriller, Seinen, Assassin, Strategy, Reincarnation, Tactical, Overpowered, Noble Society, High Society, Magic System, Martial Arts, Drama, Adventure, Romance, Mission-based",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Possibly The Greatest Alchemist Of All Time", 
    poster: "https://fr.web.img3.acsta.net/img/b6/74/b674af60032e00a9a2a7e0e233c07613.jpg", 
    alt: "Greatest Alchemist Poster",
    genre: "Fantasy • Adventure", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Studio Comet",
    rating: "⭐ 4", 
    mood: "Chill", 
    story: "After being summoned to another world, Takumi discovers his only skill is a seemingly basic 'Alchemy.' He soon realizes that his level of crafting is god-tier, allowing him to create items that defy common sense and the world's natural laws. While he only wants to live a comfortable life, his ability to produce high-quality potions and artifacts draws the attention of guilds and royalty alike.",
    hook: "A man with a 'useless' alchemy skill discovers he can craft items that break the world's laws.",
    quote: "I can make anything. If I need it, I'll just synthesize it from scratch.",
    watch: "https://aniwatchtv.to/watch/possibly-the-greatest-alchemist-of-all-time-19451?ep=131273",
    trailer: "https://www.youtube.com/embed/K1SjhnWrKLk?si=iUHSTBduGDWIh4-9",
    laugh: "https://www.youtube.com/shorts/8wFARpDLftg",
    spotify: "https://open.spotify.com/embed/album/5Utnx0hqBPbxHpE8Ffj9yi?utm_source=generator",
    keywords: "Alchemy, crafting, items, overpowered, magic, creation, laboratory, isekai, adventure, fantasy, potion, brewing, materials, discovery, skills, trading, economy, village, world-building, exploration, research, knowledge, transmutation, wealth, friendship, journey, growth, magical-items, success, strategy, takumi, alchemist, synthesis, guild, shop, materials, creation, fantasy-crafting, herbs, cauldron, fire, water, wind, earth, gold, silver, lead, and philosopher-stone.",
    keyGenre: "Isekai, Fantasy, Adventure, Shonen, Overpowered, Crafting, Alchemy, Slice of Life, World Building, Economy, Magic System, Trading, Relaxing, Research, Journey, RPG Mechanics, Discovery",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Cheat Magician", 
    poster: "https://m.media-amazon.com/images/M/MV5BNGU1YzdiY2QtOThkZi00YmU4LWFkNGItMGE3MDEwNWNmN2U0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Cheat Magician Poster",
    genre: "Fantasy • Action", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Encourage Films",
    rating: "⭐ 3", 
    mood: "Generic", 
    story: "Taichi and Rin are normal high school students who are suddenly summoned to the world of Altia. During their assessment, they discover they possess magical power and mana capacity that far exceeds anyone else in history. As 'Cheat Magicians,' they must learn to control their overwhelming power to survive dangerous monsters and stop a conspiracy that threatens to plunge the kingdom into war.",
    hook: "Two friends are summoned to a fantasy world with magical power that is literally a 'cheat' code.",
    quote: "We're cheats. This level of power shouldn't even be possible in this world.",
    watch: "https://aniwatchtv.to/watch/isekai-cheat-magician-9632?ep=49087",
    trailer: "https://www.youtube.com/embed/NH_lYSh38N8?si=u0ox23p_CArFI7Xr",
    laugh: "https://www.youtube.com/watch?v=y38jAge7zsY",
    spotify: "https://open.spotify.com/embed/playlist/18W541N3XRvS4jNt7Hh5EO?utm_source=generator",
    keywords: "Cheat-powers, isekai, magic, stats, overpowered, friends, fantasy, action, summoning, parallel-world, spells, elements, mana, combat, quest, adventure, survival, friendship, growth, monsters, leveling, hero, journey, hidden-potential, special-abilities, exploration, kingdom, magic-circles, battle, power, taichi, rin, elsa, myura, elements, cheat, magic, summoning, world-saving, portals, light, dark, dragons, knights, and friendship-power.",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Overpowered, Magic System, Adventure, Battle, Supernatural, Quest, Friendship, Survival, Kingdom Fantasy, Summoning, Journey, Leveling, Elements",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Assassin Pride", 
    poster: "https://m.media-amazon.com/images/M/MV5BMzkwMmE2YjMtNDY5MC00ZDFjLWFhNWEtNjMwN2RmNGIyZGRhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Assassin Pride Poster",
    genre: "Fantasy • Mystery", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "EMT Squared",
    rating: "⭐ 3", 
    mood: "Elegant", 
    story: "In a world where only nobles possess mana to fight monsters, Melida is a noble girl who has yet to manifest any power. Kufa is an assassin sent to be her tutor, with secret orders to kill her if she is found to be talentless. Moved by her pride and determination, Kufa chooses to defy his mission and help her fake her magic through a forbidden method, leading them into a web of aristocratic conspiracy.",
    hook: "An assassin sent to execute a talentless noble girl chooses to train her in secret instead.",
    quote: "I'll protect your pride. Even if the world says you have no mana, I'll show them your worth.",
    watch: "https://aniwatchtv.to/watch/assassins-pride-8067?ep=47027",
    trailer: "https://www.youtube.com/embed/R3myMLXpYjI?si=PIi5OnoyxwyPEsQh",
    laugh: "https://www.youtube.com/watch?v=LPKAqaQ3brI",
    spotify: "https://open.spotify.com/embed/playlist/0GRUhsa81CCKIJkcNz7KT3?utm_source=generator",
    keywords: "Assassin, student, noble, mana, bloodline, teaching, secrets, hidden-power, gothic, fantasy, mystery, combat, shadows, loyalty, protection, blade, magic, status, hierarchy, mission, skills, dark, elegant, world-building, rivalry, duty, training, destiny, swordplay, intrigue, kufa, vampir, melida, angel, flandore, mana, aristocrat, tutorship, bloodlines, vampires, moonlight, lanterns, cages, lace, daggers, and class-status.",
    keyGenre: "Fantasy, Mystery, Seinen, Action, Supernatural, Assassin, School Life, Magic System, Noble Society, High Society, Gothic, Dark Fantasy, Romance, Drama, Secret Identity, Martial Arts, Tutorship",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Seirei Gensouki", 
    poster: "https://m.media-amazon.com/images/I/71Va6PGC+RL._AC_UF894,1000_QL80_.jpg", 
    alt: "Seirei Gensouki Poster",
    genre: "Adventure • Fantasy", 
    season: "⏳ 2",
    episodes: "▶️ 24",
    studio: "TMS Entertainment",
    rating: "⭐ 4", 
    mood: "Nostalgic", 
    story: "Season 1: Rio is a street orphan living in a fantasy slums. After waking up with the memories of a Japanese student, he discovers vast hidden magical potential. After saving a kidnapped princess, he is enrolled in a royal academy where he faces discrimination. Season 2: Following his departure from the kingdom, Rio travels to his parents' homeland, discovering his true heritage and forging contracts with powerful spirits. As he grows in strength, he navigates a world on the brink of war while seeking those from his past life.",
    hook: "An orphan slum-dweller awakens past-life memories and incredible magic to change his fate.",
    quote: "I remember everything. My past life and this one... I'll find my own path in this world.",
    watch: "https://aniwatchtv.to/watch/spirit-chronicles-17333?ep=78673",
    trailer: "https://www.youtube.com/embed/PZv-KkVyZNc?si=G94qLhwTtccJaa4w",
    laugh: "https://www.youtube.com/watch?v=3mB9R4HoUAs",
    spotify: "https://open.spotify.com/embed/playlist/763FNngr4oebiMAE9MM8ve?utm_source=generator",
    keywords: "Memories, reincarnation, orphan, noble, magic, spirits, journey, revenge, betrayal, past-life, skills, adventure, fantasy, academy, combat, travel, world, identity, search, survival, power, friendship, destiny, spirits, element, swords, training, magic-arts, discovery, rio, amakawa, celia, latifa, miharu, spirits, betrayal, revenge, swordplay, haruto, memories, contracts, beast-folk, kingdom, and travel.",
    keyGenre: "Isekai, Fantasy, Adventure, Action, Shonen, Reincarnation, Overpowered, Magic System, Revenge, Drama, Noble Society, High Society, Journey, Past Life, Spirits, Martial Arts, Survival",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "No Longer Allowed In Another World", 
    poster: "https://m.media-amazon.com/images/M/MV5BYjEwNWYzYmUtZTlmYi00OTA3LTljOTEtYTVmZjNiNTQyYTAxXkEyXkFqcGc@._V1_.jpg", 
    alt: "No Longer Allowed Poster",
    genre: "Comedy • Fantasy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Atelier Pontdarc",
    rating: "⭐ 5", 
    mood: "Nihilistic", 
    story: "Based on the life of Osamu Dazai, a famous depressed author is summoned to another world with his lover while attempting a double suicide. Rather than seeking adventure, he views the fantasy world's tropes with nihilistic disdain. Using his literary wit and a complete lack of self-preservation, he inadvertently disrupts the destiny of the world while looking for a quiet place to end his journey.",
    hook: "A suicidal 20th-century author is summoned as a hero and finds the fantasy world incredibly annoying.",
    quote: "Is there a good place to die here? This world is too bright for someone like me.",
    watch: "https://aniwatchtv.to/watch/no-longer-allowed-in-another-world-19247?ep=126001",
    trailer: "https://www.youtube.com/embed/UwO5I3ZsZvA?si=V82mpy6ZvlqrhcZy",
    laugh: "https://www.youtube.com/watch?v=3mB9R4HoUAs",
    spotify: "https://open.spotify.com/embed/playlist/763FNngr4oebiMAE9MM8ve?utm_source=generator",
    keywords: "Author, suicidal, dark-humor, isekai, subversion, literary, satire, depressing, comedy, adventure, monsters, strange, hero, journey, writing, cynical, fantasy, parody, irony, unusual, quest, skills, death, life, existence, perspective, storytelling, narrative, gloom, wit, sensei, daza, annette, tama, poisons, literature, dark, satire, nihilism, pens, ink, paper, tragedy, comedy, and strange-hero.",
    keyGenre: "Isekai, Dark Comedy, Satire, Seinen, Psychological, Dark Fantasy, Philosophical, Literary, Parody, Adventure, Subversion, Nihilism, Life Lessons, Historical Figure, Surreal, Drama, Wit",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "May I Ask for One Final Thing?",
    poster: "https://fwmedia.fandomwire.com/wp-content/uploads/2025/10/07125423/may-i-ask-for-one-final-thing-episode-2.jpg", 
    alt: "Final Thing Poster",
    genre: "Action • Romance", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Fanworks",
    rating: "⭐ 5", 
    mood: "Cathartic", 
    story: "Scarlet is a refined noblewoman who has spent her life maintaining a mask of politeness despite constant mistreatment. When her engagement is publicly annulled by a spoiled prince in a crowded ballroom, her patience finally evaporates. She asks for one last favor: the permission to beat every person who slandered her into the ground, sparking a journey of martial-arts fueled retribution against a corrupt aristocracy.",
    hook: "A polite noblewoman finally snaps and asks to punch everyone in the room before her engagement ends.",
    quote: "May I punch every single one of you in the face?",
    watch: "https://aniwatchtv.to/watch/may-i-ask-for-one-final-thing-19927?ep=145501",
    trailer: "https://www.youtube.com/embed/4K4ZK_Nxigc?si=4WHq-n-6VZCCpyAg",
    laugh: "https://www.youtube.com/watch?v=l7J0q1GSR0M",
    spotify: "https://open.spotify.com/embed/playlist/6I7ukJPW0ZydnaS1hqcOQK?utm_source=generator",
    keywords: "Fist-fight, noble, engagement, broken, punch, action, lady, romance, dignity, strength, retribution, justice, etiquette, brute-force, noblewoman, elegance, combat, marriage, villain, satisfaction, comedy, drama, power, skills, nobility, impact, catharsis, resilience, style, scarlet, punch, villainess, satisfaction, brawling, beauty, justice, ballroom, dresses, gloves, and blood.",
    keyGenre: "Action, Romance, Shoujo, Drama, Fantasy, Noble Society, High Society, Retribution, Villainess, Martial Arts, Comedy, Justice, Satisfaction, Social Satire, Brawling, Historical Fantasy, Resilience",
    trending: false,
    best: false,
    gold: false, silver: true, bronze: false
  },
  { 
    name: "My Status as an Assassin Obviously Exceeds the Hero's",
    poster: "https://resizing.flixster.com/MpjKwK0ga7NTeDfOtXi-OmS1IMQ=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p30870171_b_h9_aa.jpg", 
    alt: "My Status as an Assassin Poster",
    genre: "Isekai • Action", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Studio Mother",
    rating: "⭐ 3", 
    mood: "Stealthy", 
    story: "Akira and his classmates are summoned to a fantasy world as legendary heroes. While his classmates receive flashy 'Hero' and 'Sage' classes, Akira is assigned the 'Assassin' class. He quickly realizes that while the others are treated like celebrities, his stealth stats and lethality are actually far superior to theirs. Using his invisibility, he begins to investigate the kingdom's true motives for the summoning.",
    hook: "A 'weak' assassin student finds his hidden stats dwarf the Hero's legendary power.",
    quote: "I'm the one in the shadows. The hero may have the light, but I have the truth.",
    watch: "https://aniwatchtv.to/watch/my-status-as-an-assassin-obviously-exceeds-the-heros-19922",
    trailer: "https://www.youtube.com/embed/J3uggaS9Ubg?si=urR9zkXV9fMEpMgh",
    laugh: "https://www.youtube.com/shorts/Kp8zeXlFbEw",
    spotify: "https://open.spotify.com/embed/playlist/1ZjuIvU6jY2MxOchQHZ06y?utm_source=generator",
    keywords: "Protagonist, Invisible, Presence, Summoned, Kingdom, Conspiracy, Shadows, Overpowered, Leveling, Experience, Growth, Justice, Corruption, Daggers, Agility, Speed, Perception, Instinct, Trap, Ambush, Escape, Survival, Journey, Ruins, Ancient, Mythical, Spirit, Magic, Element, Swordplay, Archery, Strategy, Tactics, Warfare, Mercenary, Guild, Reward, Bounty, Outlaw, Legend, Myth, Dark, Light, Contrast, Fate, Destiny, Prophecy, World, Dimension, Gate, Travel, Forest, Mountain, Underground, Secret, Whisper, Silence, Calm, Cold, Analytical, Emotion, Friendship, Bond, Loyalty, Protection, Guardian, Savior, Antihero, Gray, Moral, Choice, Consequence.",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Assassin, Overpowered, Revenge, Betrayal, Leveling, RPG Mechanics, Survival, Dark Fantasy, Strategy, Secret Identity, Adventure, Kingdom Intrigue, Tactical",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "No Game No Life", 
    poster: "https://m.media-amazon.com/images/M/MV5BMjRjMTA3ZDktZDBhMy00NjhjLTk1ODMtODU5NWE2NWExNzYxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "No Game No Life Poster",
    genre: "Game • Strategy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Madhouse",
    rating: "⭐ 5", 
    mood: "Competitive", 
    story: "Sora and Shiro are genius gamer siblings who find the real world boring. After being challenged to a chess match by a god, they are summoned to Disboard, a world where all violence is forbidden and every conflict—from border disputes to personal property—is decided by high-stakes games. The duo sets out to unite the 16 races of Disboard and eventually challenge the God of Games himself to a rematch.",
    hook: "Two hikikomori geniuses are summoned to a world where everything is decided by high-stakes games.",
    quote: "Blank never loses. In a world ruled by games, we are the absolute masters.",
    watch: "https://aniwatchtv.to/watch/no-game-no-life-261?ep=5328",
    trailer: "https://www.youtube.com/embed/ETQUp-Omp-A?si=-iCE52Y0xIPmiOS_",
    laugh: "https://www.youtube.com/watch?v=8tg0SQJ4-Fg",
    spotify: "https://open.spotify.com/embed/playlist/5mNBbq9LGBPm9nYGoakZfj?utm_source=generator",
    keywords: "Games, logic, strategy, siblings, hikikomori, genius, fantasy, bets, rules, chess, cards, colorful, isekai, world, stakes, tactics, mind-games, psychological, manipulation, race, kingdom, gods, magic, humor, competition, play, victory, calculations, intelligence, neon, sora, shiro, blank, stephanie, jibril, tet, disboard, pledges, imanity, flugel, warbeast, elves, dhampir, siren, and ex-machina.",
    keyGenre: "Isekai, Game, Strategy, Shonen, Comedy, Psychological, Overpowered, Mind Games, Logic, Ecchi, Adventure, Fantasy, Tactics, Supernatural, World Conquest, Colorful, Parody, Stakes, Siblings",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Rising Of The Shield Hero", 
    poster: "https://m.media-amazon.com/images/I/81YJ8CeI7hL._AC_UF894,1000_QL80_.jpg", 
    alt: "Shield Hero Poster",
    genre: "Action • Adventure", 
    season: "⏳ 3",
    episodes: "▶️ 50",
    studio: "Kinema Citrus",
    rating: "⭐ 4", 
    mood: "Spiteful", 
    story: "Season 1: Naofumi is summoned as the Shield Hero, but is betrayed and falsely accused by the kingdom. He becomes a survivalist, building power through defensive ingenuity. Season 2: Naofumi and his party face the Spirit Tortoise and travel to another dimension to stop a global threat. Season 3: Following the battle against the Spirit Tortoise, Naofumi must rebuild his territory while participating in underground arenas to free demi-human slaves, all while preparing for the inevitable return of the Waves of Catastrophe.",
    hook: "Betrayed and hated by the world, a hero with only a shield must find a way to survive and fight.",
    quote: "I'll protect them my way. I don't need your recognition to save this world.",
    watch: "https://aniwatchtv.to/watch/the-rising-of-the-shield-hero-524?ep=10509",
    trailer: "https://www.youtube.com/embed/rKnyi3TRznA?si=94pZNKj-N9NMtfjd",
    laugh: "https://www.youtube.com/watch?v=vfb211rgwss",
    spotify: "https://open.spotify.com/embed/playlist/4iueEe9seov8iSfODk0KtF?utm_source=generator",
    keywords: "Shield, betrayal, resentment, isekai, defense, legendary-weapon, survival, growth, slaves, companion, dragon, waves, catastrophe, kingdom, lies, truth, redemption, adventure, fantasy, action, revenge, protection, skills, upgrading, iron-will, resilience, strategy, struggle, justice, naofumi, raphtalia, filo, melty, motoyasu, ren, itsuki, malty, waves, balloons, and rage-shield.",
    keyGenre: "Isekai, Action, Adventure, Seinen, Drama, Fantasy, Dark Fantasy, Betrayal, Redemption, Survival, Revenge, Strategy, RPG Mechanics, Leveling, Political Intrigue, Psychology, Resilience, Monster Hunter",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "That Time I Got Reincarnated as a Slime", 
    poster: "https://m.media-amazon.com/images/M/MV5BNWU3OTRlNWMtZGQyOC00YzJhLWIyNjctYmI2YzgyZTQ3ZDNmXkEyXkFqcGc@._V1_.jpg", 
    alt: "Slime Isekai Poster",
    genre: "Fantasy • Adventure", 
    season: "⏳ 3",
    episodes: "▶️ 72",
    studio: "Eight Bit",
    rating: "⭐ 2", 
    mood: "Triumphant", 
    story: "Season 1: A salaryman is reborn as a Slime in a cave. By devouring everything, he gains god-like skills and builds a monster nation. Season 2: To save his people, Rimuru evolves into a Demon Lord and confronts the Council of Saints and the Demon Lord Clayman. Season 3: Now a recognized Demon Lord, Rimuru organizes a massive festival to introduce the nation of Tempest to the human world, leading to new diplomatic challenges and a showdown with the Holy Empire of Lubelius.",
    hook: "A salaryman is reborn as a slime with the power to absorb any skill and builds a nation of monsters.",
    quote: "I'm not a bad slime. I just want to build a world where everyone can smile.",
    watch: "https://aniwatchtv.to/that-time-i-got-reincarnated-as-a-slime-429",
    trailer: "https://www.youtube.com/embed/qE27ziji4Wc?si=hZCmtF0KmNp0O3Pn",
    laugh: "https://www.youtube.com/watch?v=UJ8F-zWxi1M",
    spotify: "https://open.spotify.com/embed/playlist/0w65Vz1JKBClb3QzSDCaQX?utm_source=generator",
    keywords: "Slime, nation-building, skills, monsters, absorption, evolution, isekai, fantasy, magic, diplomacy, kingdom, war, friendship, overpowered, predator, sage, dragon, community, growth, world-building, adventure, names, transformation, strategy, alliance, civilization, culture, diversity, magic-theory, leader, rimuru, tempest, veldora, shion, benimaru, milim, shuna, Jura, and goblin.",
    keyGenre: "Isekai, Fantasy, Adventure, Shonen, Overpowered, Nation Building, World Building, Magic System, Monster, Diplomacy, Politics, Evolution, Comedy, Action, Strategy, Civilization, Community, War",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Tsukimichi", 
    poster: "https://m.media-amazon.com/images/M/MV5BZGFjZDJkOWYtOTgwYy00MTI4LWJlNDItZWI1MWY4ZmY1ZDllXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Tsukimichi Poster",
    genre: "Action • Fantasy", 
    season: "⏳ 2",
    episodes: "▶️ 37",
    studio: "C2C",
    rating: "⭐ 5", 
    mood: "Spiteful", 
    story: "Season 1: Makoto Misumi is summoned to a fantasy world but rejected by the goddess for being 'ugly.' Dumped in a wasteland, he discovers his human body has god-like strength and he builds a hidden monster city. Season 2: Makoto travels to the human academy as a teacher to expand his trading company. While he tries to stay out of the divine war between humans and demons, his overwhelming power and the expansion of his sub-space city make him a player that no god or king can ignore.",
    hook: "Rejected by a goddess for his looks, a boy builds a thriving monster kingdom in a wasteland.",
    quote: "I'll make my own path. If the gods won't help me, I'll build my own world.",
    watch: "https://aniwatchtv.to/watch/tsukimichi-moonlit-fantasy-17241?ep=78728",
    trailer: "https://www.youtube.com/embed/U8T63kIny7E?si=5takzrvu-mc3akRR",
    laugh: "https://www.youtube.com/watch?v=RoNTAovjVwc",
    spotify: "https://open.spotify.com/embed/playlist/4wEA8MSiEw1ikt4pYKIw5F?utm_source=generator",
    keywords: "Ugly-hero, banished, god-blessing, moon, monsters, isekai, trade, commerce, village, overpowered, archery, spirits, dragon, spider, comedy, fantasy, world, building, society, magic, battle, survival, skills, demi-humans, adventure, communication, status, power, transformation, journey, makoto, misumi, tomoe, mio, shiki, goddess, wasteland, asora, archery, and pig-folk.",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Overpowered, Comedy, World Building, Adventure, Magic System, Trade, Commerce, Mythology, Society, Parody, Supernatural, Monster, Survival",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Black Summoner", 
    poster: "https://m.media-amazon.com/images/M/MV5BYmU2ZGFkY2MtYTVlOS00ZmExLThjMzMtY2MwMWFiYTBmMDA3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Black Summoner Poster",
    genre: "Action • Fantasy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Satelight",
    rating: "⭐ 4", 
    mood: "Addictive", 
    story: "Kelvin woke up in a new world with no memories, having traded them away to a goddess for god-level summoning skills. He is a 'battle junkie' who lives for the thrill of challenging powerful enemies. He hides his true S-rank strength by posing as an ordinary adventurer while contracting with legendary knights and demons to build the world's most lethal party.",
    hook: "A battle-junkie trades his memories for god-level summoning skills to fight the world's strongest.",
    quote: "I live for the thrill of the fight. Every contract I make is a step toward a stronger enemy.",
    watch: "https://aniwatchtv.to/watch/black-summoner-18088?ep=92676",
    trailer: "https://www.youtube.com/embed/mgRiBleE3g4?si=qeCz0fuCNtdQm6SG",
    laugh: "https://www.youtube.com/shorts/LnEenMs10bk",
    spotify: "https://open.spotify.com/embed/playlist/4XSqZNSXpXo1KmS752RTgg?utm_source=generator",
    keywords: "Summoner, memories, trade, overpowered, battle-junkie, isekai, magic, skills, contracts, demon-lord, adventure, leveling, action, combat, goddess, party, fantasy, growth, monsters, spells, weapons, stats, thrill, victory, training, development, summoning, tactical, strategy, power, kelvin, melfina, efil, gerard, sera, summoning, battle-junkie, stats, and dark-magic.",
    keyGenre: "Isekai, Action, Fantasy, Shonen, Overpowered, Magic System, Battle Junkie, RPG Mechanics, Leveling, Summoning, Adventure, Monsters, Combat, Strategy, Supernatural, Thriller",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Devil Is A Part-Timer!", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpSG1aqAKAKoKUSUWrZXLzaFNBUKdZxg-jVQ&s", 
    alt: "Devil Is A Part-Timer Poster",
    genre: "Comedy • Fantasy", 
    season: "⏳ 3",
    episodes: "▶️ 37",
    studio: "Studio 3Hz",
    rating: "⭐ 2", 
    mood: "Mundane", 
    story: "Season 1: Demon Lord Satan escapes to modern-day Tokyo and, stripped of his powers, starts flipping burgers at MgRonald’s. Season 2: As more characters from Ente Isla arrive, the group must deal with a mysterious baby named Alas Ramus. Season 3: Maou and the others continue their mundane lives in Tokyo while dealing with celestial interference from Ente Isla. Between shifts at the burger joint and keeping up with the rent, Maou must navigate being a surrogate father and a former conqueror trying to live peacefully.",
    hook: "The Demon Lord is forced to escape to modern Tokyo and take a part-time job at a fast-food joint.",
    quote: "I will conquer this world... starting with the regional manager position!",
    watch: "https://aniwatchtv.to/watch/the-devil-is-a-part-timer-724?ep=12930",
    trailer: "https://www.youtube.com/embed/LtudWW5_4Do?si=imAw2orhuDlROL4V",
    laugh: "https://www.youtube.com/watch?v=CJLQ-SSIG0g",
    spotify: "https://open.spotify.com/embed/playlist/3jVjEEJw6AU1EMFMkK2RvC?utm_source=generator",
    keywords: "Satan, fast-food, reverse-isekai, comedy, burger, hero, magic, modern-world, poverty, survival, employment, humor, demon-king, battle, urban-fantasy, slice-of-life, manager, service, competition, irony, supernatural, interaction, daily-life, struggles, humor, mundane, transition, power-loss, fun, maou, emi, ashiya, chiho, mgronald, enta-isla, and economy.",
    keyGenre: "Reverse Isekai, Comedy, Fantasy, Slice of Life, Shonen, Workplace Drama, Supernatural, Urban Fantasy, Satire, Daily Life, Modern, Parody, Humor, Demon Lord, Action, Romance, Social Satire",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Hero Without a Class", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDF0r__S0_oQVyqNnSrCz7kDyG90_zLgXVLw&s", 
    alt: "Hero Without a Class: Who Even Needs Skills?! Poster",
    genre: "Action • Adventure", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Studio A-Cat",
    rating: "⭐ 5", 
    mood: "Determined", 
    story: "In a world where a goddess bestows classes and skills at age ten, Arel—the son of a legendary Sword Princess and an Archmage—is born classless. Undeterred by the lack of divine gifts, he relies on relentless physical training and strategic ingenuity. He begins a journey to prove that mastery earned through grit and natural talent can surpass any pre-ordained destiny.",
    hook: "The son of legendary heroes is born without a class and must prove that hard work beats destiny.",
    quote: "I understand I can still learn what others were simply given.",
    watch: "https://aniwatchtv.to/watch/hero-without-a-class-who-even-needs-skills-19912?ep=145012",
    trailer: "https://www.youtube.com/embed/_CMcsEsMaSQ?si=nf0gmbgBij1vwm42",
    laugh: "https://www.youtube.com/shorts/WHlnzp-W4qs",
    spotify: "https://open.spotify.com/embed/playlist/2VTj7cH3etVNk7AnzkRnfL?utm_source=generator",
    keywords: "Classless, adventurer, training, sword-princess, archmage, fantasy, action, skills, determination, grit, hero, guild, bresgia, dragon-fang, hard-work, zero-to-hero, talent, goddess, blessing, rituals, age-ten, parents, legacy, swordplay, magic, mastery, evolution, combat, monster-hunting, exploration, party-members, growth, potential, defiance, social-stigma, underdog, destiny, rewriting-fate, strength, physical-prowess, technique, library, forbidden-knowledge, secrets, and journey.",
    keyGenre: "Action, Adventure, Fantasy, Shonen, Underdog, Zero to Hero, Training, Martial Arts, Magic System, Swordplay, Determination, Grit, Heroic Fantasy, Growth, Exploration, Battle",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Ossan Newbie Adventurer", 
    poster: "https://m.media-amazon.com/images/M/MV5BNWE0YjE3YWEtMmM2Mi00MzM0LWJiZDktZGRjM2FiNmU0MDAyXkEyXkFqcGc@._V1_.jpg", 
    alt: "The Ossan Newbie Adventurer Poster",
    genre: "Action • Comedy", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Yumeta Company",
    rating: "⭐ 5", 
    mood: "Inspirational", 
    story: "At 30 years old, Rick Gladiator leaves his stable job as a guild clerk to finally pursue his dream of becoming an adventurer. Although he is officially an F-rank newbie, he spent years being 'trained to death' by the continent's strongest party, Orichalcum Fist. Unaware of his own god-tier strength, he inadvertently crushes powerful rivals while trying to pass basic entry exams.",
    hook: "A 30-year-old 'old man' starts his adventuring career with secret S-rank power.",
    quote: "I'll show them what an 'ossan' can really do!",
    watch: "https://aniwatchtv.to/watch/the-ossan-newbie-adventurer-trained-to-death-by-the-most-powerful-party-became-invincible-19219?ep=125747",
    trailer: "https://www.youtube.com/embed/j3bD6B-oIt4?si=GurLbxh9uIj4TfFK",
    laugh: "https://www.youtube.com/shorts/zeD2_rTcqco",
    spotify: "https://open.spotify.com/embed/playlist/1F4UIGL2rg5vYINHwUfq6R?utm_source=generator",
    keywords: "Ossan, newbie, adventurer, overpowered, training, comedy, fantasy, s-rank, guild-clerk, orichalcum-fist, rick-gladiator, adventure, late-bloomer, brutal-training, invincible, hidden-strength, monsters, exam, ranking, guild, combat, fist-fight, physical-power, humor, parody, party, legend, veteran, retired, desk-job, dreams, persistence, strength, speed, stamina, monsters, dungeon, trial, qualification, rejection, success, and journey.",
    keyGenre: "Action, Comedy, Fantasy, Shonen, Overpowered, Underdog, Training, Late Bloomer, Parody, Adventure, Battle, Martial Arts, Guild Life, Hidden Strength, Humor",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Reason Why Raeliana Ended up at the Duke's Mansion", 
    poster: "https://m.media-amazon.com/images/M/MV5BYmY3MzIyMTktZmU0My00MjkzLTkzNzgtYmQzYjg1NDA0YjBkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "The Reason Why Raeliana Ended up at the Duke's Mansion Poster",
    genre: "Romance • Mystery", 
    season: "⏳ 1",
    episodes: "▶️ 12",
    studio: "Typhoon Graphics",
    rating: "⭐ 5", 
    mood: "Suspenseful", 
    story: "After a mysterious death, a modern woman is reborn as Raeliana McMillan, a character in a novel destined to be poisoned by her own fiancé. To rewrite her tragic ending, she uses her knowledge of the future to blackmail the powerful and manipulative Duke Noah Wynknight into a fake engagement for protection. However, she soon finds that the cold-hearted Duke may have his own secret agenda.",
    hook: "To avoid her destined murder, she enters a dangerous contract with a cold-hearted duke.",
    quote: "I'm going to rewrite this story and survive, no matter what it takes.",
    watch: "https://aniwatchtv.to/watch/the-reason-why-raeliana-ended-up-at-the-dukes-mansion-18350?ep=100104",
    trailer: "https://www.youtube.com/embed/ptYa6u0dLNk?si=pR04Ge1w1Z7nL7Db",
    laugh: "https://www.youtube.com/shorts/6FC18XjpFYw",
    spotify: "https://open.spotify.com/embed/playlist/5n0nv97qOlTQuEhMJ1M6aL?utm_source=generator",
    keywords: "Isekai, romance, mystery, contract-engagement, duke, reincarnation, novel-world, survival, drama, thriller, raeliana, noah-wynknight, fate, betrayal, murder, plot, noble, palace, court-intrigue, manipulation, cold-duke, secrets, fiance, villainess, protection, deals, survival-instinct, cunning, intelligence, historical-setting, magic, society, high-society, balls, scandals, investigation, toxins, threats, gun, marksmanship, tea, flowers, and romantic-tension.",
    keyGenre: "Isekai, Romance, Fantasy, Mystery, Shoujo, Reincarnation, Otome, Noble Society, High Society, Political Intrigue, Drama, Contract Relationship, Survival, Thriller, Historical Fantasy, Court Drama",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  }
];
