window.kdramas = [
  { 
    name: "My Demon", 
    poster: "https://image.tmdb.org/t/p/original/zthWx1TKEXy9MOfedBaJ0ZLr8vn.jpg", 
    alt: "My Demon Poster",
    genre: "Fantasy • Romance", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio S",
    rating: "⭐ 2",
    mood: "Fated", 
    story: "Gu-won is a pitiless demon who has spent centuries making deals with humans. His life changes instantly when his powers are accidentally transferred to Do Do-hee, a cold and cynical heiress to a business conglomerate. To prevent his own extinction and protect his pride, he must act as her bodyguard while they navigate a dangerous corporate succession battle and a blossoming, fated romance.",
    hook: "A contractual marriage between a mortal heiress and a demon who lost his powers.",
    quote: "You must be the only person in the world who would use a demon as a bodyguard.",
    watch: "https://ww16.dramacool.bg/episode/98110/my-demon-2023-episode-1",
    trailer: "https://www.youtube.com/embed/D-bAfFqvxZg?si=_HwvVSty5mHHmcRf",
    laugh: "https://www.youtube.com/shorts/9ZYh1tr3Vbw",
    spotify: "https://open.spotify.com/embed/album/7lN1utee2goYJ0mMtgUevB?utm_source=generator",
    keywords: "Demon, contract marriage, supernatural, romance, heiress, power loss, bodyguard, fate, soul, mystery, immortal, enemies to lovers, chaebol, protector, tattoo transfer, paranormal romance, visual chemistry, past life, reincarnation, redemption, sacrifice, divine intervention, corporate war, internal conflict, dark humor, guardian, deal with the devil, eternal love, emotional healing, fated encounter.",
    keyGenre: "Fantasy, Romance, Comedy, Supernatural, Thriller, Melodrama, Mystery, Paranormal, Action, Drama, Business, Suspense, Urban Fantasy, Contemporary, Psychological",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Glory", 
    poster: "https://image.tmdb.org/t/p/original/uUM4LVlPgIrww07OoEKrGWlS1Ej.jpg", 
    alt: "The Glory Poster",
    genre: "Thriller • Revenge", 
    episodes: "▶️ 16",
    season: "⏳ 2",
    studio: "Hwa&Dam Pictures",
    rating: "⭐ 5",
    mood: "Meticulous", 
    story: "Season 1: Years after surviving horrific abuse in high school, Moon Dong-eun puts an elaborate revenge scheme in motion, positioning herself as the homeroom teacher to her main tormentor's child. <br><br> Season 2: The revenge reaches its peak as the perpetrators' lives crumble under the weight of their own secrets and Dong-eun's meticulous planning, leading to a dark and poetic conclusion for her lifelong mission.",
    hook: "A victim of brutal school violence dedicates her life to a meticulous revenge plot.",
    quote: "There will be no glory for you, so I hope you will be destroyed too.",
    watch: "https://ww16.dramacool.bg/episode/94677/the-glory-2022-episode-1",
    trailer: "https://www.youtube.com/embed/tqVVrTvrI8U?si=tEMuGvpI9U_-9FTM",
    laugh: "youtube.com/watch?v=P4wu3aPXm6o&pp=ygUWdGhlIGdsb3J5IGxhdWdoIG1vbWVudA%3D%3D",
    spotify: "https://open.spotify.com/embed/album/0OR9LHwVKfeRjkHxcDm1mc?utm_source=generator",
    keywords: "Revenge, school bullying, psychological thriller, justice, survival, manipulation, trauma, architecture, Go game, victim empowerment, long-term planning, social class, consequences, dark, obsession, meticulous, poetic justice, betrayal, trauma recovery, calculated risk, secret, conspiracy, moral ambiguity, emotional scars, justice system, cold blooded, strategic, alliance, reckoning, high stakes.",
    keyGenre: "Thriller, Noir, Drama, Revenge, Psychological, Crime, Suspense, Melodrama, Mystery, Social Issues, Tragedy, Dark, Intense, Legal, Human Rights",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Sweet Home", 
    poster: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p19174483_b_v8_aa.jpg", 
    alt: "Sweet Home Poster",
    genre: "Horror • Action", 
    episodes: "▶️ 28",
    season: "⏳ 3",
    studio: "Studio Dragon",
    rating: "⭐ 4",
    mood: "Apocalyptic", 
    story: "Season 1: Residents of the Green Home apartment building fight to survive as a mysterious phenomenon turns humans into monsters reflecting their inner desires. <br><br> Season 2: The survivors venture into the outside world, facing a military-run camp and the evolution of 'neo-humans'. <br><br> Season 3: The final struggle between humans, monsters, and neohumans reaches its climax as Cha Hyun-su battles to regain his humanity and end the nightmare.",
    hook: "In an apocalyptic world, your deepest desires turn you into a monster.",
    quote: "Even the deepest darkness is vanished by the smallest light.",
    watch: "https://ww16.dramacool.bg/episode/89567/sweet-home-2020-episode-1",
    trailer: "https://www.youtube.com/embed/7rI56NmD33Y?si=l6B72xH6-MXKvslr",
    laugh: "https://www.youtube.com/watch?v=e34czuA3ToM&pp=ygUXU3dlZXQgSG9tZSBsYXVnaCBtb21lbnQ%3D",
    spotify: "https://open.spotify.com/embed/album/7AXjOCk3yYNaIeJyD8arNm?utm_source=generator",
    keywords: "Monster, apocalypse, survival, webtoon, horror, apartment, human desire, transformation, supernatural, survival horror, psychological struggle, isolation, community, fighting, survival instincts, gore, mutation, military, government conspiracy, inner demon, evolution, chaos, heroism, loss, hope, fear, dystopian, teamwork, moral dilemma, neohuman.",
    keyGenre: "Horror, Action, Sci-Fi, Supernatural, Thriller, Gore, Survival, Dystopian, Psychological, Fantasy, Adventure, Drama, Mystery, Post-Apocalyptic, Creature Feature",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Bloodhounds", 
    poster: "https://m.media-amazon.com/images/M/MV5BNjU2NThhZWYtN2MxMy00MzExLTlhOTYtNDk1YmUxY2I3YzdhXkEyXkFqcGc@._V1_.jpg", 
    alt: "Bloodhounds Poster",
    genre: "Action • Noir", 
    episodes: "▶️ 8",
    season: "⏳ 1",
    studio: "Studio N",
    rating: "⭐ 5", 
    mood: "Gritty",
    story: "Gun-woo and Woo-jin, two young boxers with heart and grit, band together with a benevolent moneylender to take down a ruthless loan shark who preys on the financially desperate. Their journey takes them deep into a dark underworld where they must use their fists and unbreakable bond to fight for justice against a mountain of corruption and violence.",
    hook: "Two boxers use their fists to fight a corrupt loan shark underworld.",
    quote: "If you want to catch a beast, you have to become a beast.",
    watch: "https://ww16.dramacool.bg/episode/95246/bloodhounds-2023-episode-1",
    trailer: "https://www.youtube.com/embed/eyiR8pO50JE?si=Wf-J029xBGJ3glfS",
    laugh: "https://www.youtube.com/watch?v=BEyNmlIe0jo&pp=ygUYQmxvb2Rob3VuZHMgbGF1Z2ggbW9tZW50",
    spotify: "https://open.spotify.com/embed/playlist/6E0nzqYjXugBqpX5FcAWcv?utm_source=generator",
    keywords: "Boxing, loan sharks, action, bromance, debt, underworld, crime, justice, fighting, hand-to-hand combat, greed, money, partnership, grit, underworld war, brotherhood, loyalty, training, revenge, corruption, underground, survival, physical endurance, debt collection, morality, sacrifice, friendship, street fight, vigilante, redemption.",
    keyGenre: "Action, Noir, Crime, Drama, Thriller, Martial Arts, Bromance, Revenge, Suspense, Sports, Underworld, Investigation, Mystery, Dark, Gritty",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Good Bad Mother", 
    poster: "https://image.tmdb.org/t/p/original/fvcEgIUZMks1cZPgZTnIHqUArtN.jpg", 
    alt: "The Good Bad Mother Poster",
    genre: "Comedy • Life", 
    episodes: "▶️ 14",
    season: "⏳ 1",
    studio: "Drama House",
    rating: "⭐ 2", 
    mood: "Healing",
    story: "Young-soon, a single mother who runs a pig farm, raised her son Kang-ho with strict 'tough love' to ensure he became a powerful prosecutor. After a tragic accident leaves Kang-ho with the mental capacity of a 7-year-old, the two return to their village. This unexpected second childhood gives them a chance to heal their broken relationship and eventually seek justice for the tragedy that shaped their lives.",
    hook: "A second chance at childhood leads to healing between a mother and son.",
    quote: "To live is to find the beauty in the small things.",
    watch: "https://ww16.dramacool.bg/episode/82171/the-good-bad-mother-2023-episode-1",
    trailer: "https://www.youtube.com/embed/CzVi_hIZ3mc?si=o_KCAFxywUCNhJaT",
    laugh: "https://www.youtube.com/watch?v=F-6KVXE1qcc",
    spotify: "https://open.spotify.com/embed/album/6AyMXsTW3icYk3am2KkuHj?utm_source=generator",
    keywords: "Motherhood, amnesia, prosecutor, rural life, healing, family, second chance, comedy, lawyer, pig farm, village life, emotional journey, regret, reconciliation, tough love, sacrifice, growth, memory, corruption, justice, childhood trauma, rural community, friendship, parenting, disability, rebirth, small town, nostalgia, bonds, tragedy.",
    keyGenre: "Life, Comedy, Family, Melodrama, Law, Slice of Life, Drama, Healing, Psychological, Rural, Legal, Mystery, Crime, Heartwarming, Coming of Age",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Love Alarm", 
    poster: "https://m.media-amazon.com/images/M/MV5BYjMyNmI4NzAtOTlmNy00NGMwLWE0YjUtYjkwNzA3MzExMzA0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Love Alarm Poster",
    genre: "Romance • Youth", 
    episodes: "▶️ 14",
    season: "⏳ 2",
    studio: "Studio Dragon",
    rating: "⭐ 3", 
    mood: "Digital",
    story: "Season 1: Kim Jojo navigates high school while a mobile app that notifies users if someone within 10 meters has romantic feelings for them becomes a global phenomenon. <br><br> Season 2: Years later, as adults, Jojo and her suitors deal with the 'Love Alarm 2.0' update, which now predicts who will fall in love with whom, forcing Jojo to confront her shielded heart and make a final choice.",
    hook: "An app that rings when someone who likes you is within 10 meters.",
    quote: "The miracle of two people liking each other at the same time.",
    watch: "https://ww16.dramacool.bg/episode/67151/love-alarm-2019-episode-1",
    trailer: "https://www.youtube.com/embed/8sXTfzaLmiQ?si=WBrKPnPw6KCmwknk",
    laugh: "https://www.youtube.com/watch?v=1xI_k89gMKI",
    spotify: "https://open.spotify.com/embed/album/40YgAw6vbUl3veNlJdCd79?utm_source=generator",
    keywords: "Mobile app, high school, love triangle, technology, romance, social media, webtoon, youth, notification, dating, heartbreak, coming of age, futuristic dating, digital age, privacy, social pressure, isolation, childhood scars, first love, loyalty, decision, algorithm, emotions, longing, adult life, friendship, betrayal, shield, ringing, connection.",
    keyGenre: "Romance, Youth, Sci-Fi, Drama, Melodrama, Contemporary, High School, Coming of Age, Psychological, Webtoon Adaptation, Friendship, Technology, Social Issues, Relationship, Love Story",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Marry My Husband", 
    poster: "https://image.tmdb.org/t/p/original/dQiZHHa23M1lbggcF6pPUF7i862.jpg", 
    alt: "Marry My Husband Poster",
    genre: "Fantasy • Revenge", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 3", 
    mood: "Empowering",
    story: "Kang Ji-won, a terminally ill woman who was murdered after witnessing her husband and best friend's affair, wakes up ten years in the past. Given a second chance at life, she decides to change her fate by ensuring her husband and traitorous friend end up together instead, all while carving out a new future for herself and finding unexpected support in her stoic boss.",
    hook: "A murdered woman travels back in time to give her husband and best friend a taste of their own medicine.",
    quote: "I'm not going to live like a victim again. This time, I'll be the one to decide my fate.",
    watch: "https://ww16.myasiantv.es/ep/marry-my-husband-2024-episode-1-english-subbed-ah/",
    trailer: "https://www.youtube.com/embed/lfJGSxXf9Xg?si=zjU4rspt9X51H8lu",
    laugh: "https://www.youtube.com/watch?v=okfEghfXqxk&pp=ygUdTWFycnkgTXkgSHVzYmFuZCBsYXVnaCBtb21lbnQ%3D",
    spotify: "https://open.spotify.com/embed/track/4dgspE323L82XYAjpnlXsv?utm_source=generator",
    keywords: "Time travel, revenge, cheating, second chance, terminal illness, corporate life, destiny, friendship betrayal, transformation, empowerment, fated romance, justice, manipulation, past life, growth, karma, strategy, love interest, office drama, resilience, survival, healing, wedding, fate change, mystery.",
    keyGenre: "Fantasy, Revenge, Romance, Drama, Melodrama, Business, Thriller, Psychological, Time Travel, Mystery",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "W: Two Worlds Apart", 
    poster: "https://image.tmdb.org/t/p/original/rBuCoS0VB9M6zkEUCvnVrfeF0J.jpg", 
    alt: "W Poster",
    genre: "Fantasy • Thriller", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Chorokbaem Media",
    rating: "⭐ 4", 
    mood: "Surreal",
    story: "Surgeon Oh Yeon-joo finds herself pulled into the world of the hit webtoon 'W', created by her father, where she saves the life of the protagonist Kang Chul. As she begins to jump between the real world and the webtoon world, the two become entangled in a race to uncover the truth behind a mysterious killer and the supernatural forces controlling their existence.",
    hook: "A surgeon gets pulled into the world of a popular webtoon and falls for its main character.",
    quote: "You're the key to my life.",
    watch: "https://www.bilibili.tv/en/video/4793209721851904?bstar_from=bstar-web.homepage.recommend.all",
    trailer: "https://www.youtube.com/embed/h_Nf1vTOy2s?si=1FwuvoKS1hgUNGA8",
    laugh: "https://www.youtube.com/shorts/S8f94kam0wA",
    spotify: "https://open.spotify.com/embed/album/55IvETu3AX6HGxxlalfDBY?utm_source=generator",
    keywords: "Webtoon, parallel worlds, romance, thriller, artist, survival, mystery, meta-fiction, destiny, identity, reality vs fiction, creator vs creation, suspense, crime, action, star-crossed lovers, portal, alternate reality, manhwa, detective, truth, memory, hospital, family secret, high stakes.",
    keyGenre: "Fantasy, Thriller, Romance, Action, Mystery, Suspense, Melodrama, Psychological, Meta-Fiction",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Doctor Stranger", 
    poster: "https://i.pinimg.com/736x/bc/16/34/bc16349f1491c6ccd0b0f9dae9584212.jpg", 
    alt: "Doctor Stranger Poster",
    genre: "Medical • Action", 
    episodes: "▶️ 20",
    season: "⏳ 1",
    studio: "Aura Media",
    rating: "⭐ 1", 
    mood: "Political",
    story: "Park Hoon, a genius heart surgeon who was raised in North Korea, escapes to the South but loses his first love in the process. While working at a prestigious South Korean hospital, he encounters a mysterious woman who looks exactly like his lost fiancée. He must navigate hospital politics, rivalry with a cold-hearted colleague, and a web of political conspiracies to find the truth about his past and protect those he loves.",
    hook: "A genius North Korean defector doctor searches for his lost love in a South Korean hospital.",
    quote: "I'm a doctor. My job is to save people.",
    watch: "https://ww16.dramacool.bg/episode/89740/doctor-stranger-2014-episode-1",
    trailer: "https://www.youtube.com/embed/ZBjdGi8HCQM?si=tzqOjpjlkVYFdcvc",
    laugh: "https://www.youtube.com/shorts/43L7JOGPHnY",
    spotify: "https://open.spotify.com/embed/album/62KWpP8uHnLeSlaD3slLMH?utm_source=generator",
    keywords: "Medical, North Korea, defector, romance, conspiracy, genius doctor, loss, search, identity, hospital politics, rivalry, surgery, sacrifice, past, trauma, secrets, action, suspense, fate, medical ethics, loyalty, first love, escape, survival, political intrigue.",
    keyGenre: "Medical, Action, Romance, Thriller, Political, Melodrama, Drama, Suspense, Mystery",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Tomorrow", 
    poster: "https://i.pinimg.com/736x/f7/b3/b2/f7b3b2feaaad234c0449ad6fdf1d6466.jpg", 
    alt: "Tomorrow Poster",
    genre: "Fantasy • Action", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio N",
    rating: "⭐ 5", 
    mood: "Empathetic",
    story: "Choi Jun-woong, a young man struggling to find a job, accidentally falls into a coma and becomes half-human and half-spirit. He is recruited by a team of Grim Reapers who work for a crisis management team in the afterlife. Unlike traditional reapers, their mission is not to collect souls, but to prevent people from taking their own lives by addressing their deep-seated pain and offering them hope for tomorrow.",
    hook: "Grim Reapers work together to save people who want to die.",
    quote: "A person's life isn't just their own. It belongs to all those who love them.",
    watch: "https://ww16.dramacool.bg/episode/85032/tomorrow-2022-episode-1",
    trailer: "https://www.youtube.com/embed/BsNRPkOV_Mo?si=6VvaCgU-JWXhm5A2",
    laugh: "https://www.youtube.com/shorts/5U4UaXNx8Gw",
    spotify: "https://open.spotify.com/embed/playlist/1yuQoflkeBxtyLAGdr7qgn?utm_source=generator",
    keywords: "Grim Reaper, afterlife, suicide prevention, healing, empathy, spirits, mission, trauma, hope, team, supernatural, destiny, choice, human connection, societal issues, sacrifice, redemption, growth, emotional, mental health, mystery, justice, past lives, life after death, crisis management.",
    keyGenre: "Fantasy, Action, Drama, Supernatural, Healing, Slice of Life, Mystery, Melodrama, Psychological",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Moving", 
    poster: "https://m.media-amazon.com/images/M/MV5BNTg4NTI5NmItNGJjNC00ZmFhLTg0NzctZWQxZjAzYTAyNTQwXkEyXkFqcGc@._V1_.jpg", 
    alt: "Moving Poster",
    genre: "Action • Sci-Fi", 
    episodes: "▶️ 20",
    season: "⏳ 1",
    studio: "Studio &NEW",
    rating: "⭐ 1", 
    mood: "Protective",
    story: "Three high school students with inherited superhuman abilities try to hide their powers while living ordinary lives. Meanwhile, their parents, who once served as black-ops agents for the government, fight to protect them from a mysterious assassin and a dark organization hunting down retired supers. As the past and present collide, the families must unite to survive a high-stakes battle for their freedom.",
    hook: "Parents with secret superpowers fight to protect their children who inherited their abilities.",
    quote: "People with superpowers are also just people.",
    watch: "https://ww16.dramacool.bg/episode/98050/moving-2023-episode-1",
    trailer: "https://www.youtube.com/embed/d_SFsZEZAy4?si=fxetsZXlVzq7U_JS",
    laugh: "https://www.youtube.com/shorts/TGxNxqOCK60",
    spotify: "https://open.spotify.com/embed/playlist/6XKAFCMi26RZHqAj5XjWRi?utm_source=generator",
    keywords: "Superpowers, family, government, agents, action, high school, secrets, protection, survival, superhuman, conspiracy, legacy, sacrifice, training, mystery, sci-fi, hidden identity, thriller, combat, special forces, parents, coming of age, justice, danger, brotherhood.",
    keyGenre: "Action, Sci-Fi, Supernatural, Thriller, Drama, Mystery, Fantasy, Youth, Family, Political",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Business Proposal", 
    poster: "https://m.media-amazon.com/images/M/MV5BYWM2NTM4MTktNDFiNi00NTI3LThiZTgtZmJiZTQ2NzdhNDE3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "Business Proposal Poster",
    genre: "Romance • Comedy", 
    episodes: "▶️ 12",
    season: "⏳ 1",
    studio: "Kross Pictures",
    rating: "⭐ 5", 
    mood: "Charming",
    story: "Shin Ha-ri agrees to go on a blind date in place of her wealthy best friend with the intention of being rejected. However, the date turns out to be her company's CEO, Kang Tae-moo. After a series of mishaps, Tae-moo decides to marry her to satisfy his grandfather's demands, leading Ha-ri to live a double life to hide her true identity as his employee while they both fall into an unexpected romance.",
    hook: "A woman goes on a blind date in place of her friend and discovers her date is her CEO.",
    quote: "I'll do my best not to fall for you.",
    watch: "https://ww16.dramacool.bg/episode/98394/a-business-proposal-2022-episode-1",
    trailer: "https://www.youtube.com/embed/mh4R-WXRhQo?si=b63nHZhLA_ClA3_9",
    laugh: "https://www.youtube.com/shorts/K1Yr5vXTidg",
    spotify: "https://open.spotify.com/embed/album/3mus1JiTJRZUfhOExy71lY?utm_source=generator",
    keywords: "Blind date, CEO, office romance, secret identity, double life, comedy, webtoon, grandfather, fake dating, contract marriage, humor, coincidence, workplace, friendship, romance, lighthearted, misunderstandings, chemistry, food research, chaebol, hidden feelings, rivals to lovers, light drama, love triangle, charming.",
    keyGenre: "Romance, Comedy, Workplace, Drama, Business, Webtoon Adaptation, Contemporary",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "What's Wrong with Secretary Kim", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu4xeNUpMx8z_qzxB0UA-N-DU7qmO98BmTzw&s", 
    alt: "Secretary Kim Poster",
    genre: "Romance • Comedy", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Bon Factory",
    rating: "⭐ 5", 
    mood: "Narcissistic",
    story: "Lee Young-joon, a narcissistic and perfectionist vice chairman, is shocked when his highly capable secretary of nine years, Kim Mi-so, suddenly announces her resignation. Determined to keep her by his side, he tries everything from bribery to marriage proposals to change her mind. In the process, they both begin to confront a shared traumatic childhood secret and realize their feelings for each other go far beyond a professional relationship.",
    hook: "A narcissistic boss tries to stop his perfect secretary from quitting.",
    quote: "I'm too perfect to be someone's secretary.",
    watch: "https://ww16.myasiantv.es/ep/whats-wrong-with-secretary-kim-2018-episode-1-english-subbed-aa/",
    trailer: "https://www.youtube.com/embed/EDGfWN36q5o?si=B-nHRpJ9C3dKeVYj",
    laugh: "https://www.youtube.com/watch?v=OAJ6fqMcTQ0",
    spotify: "https://open.spotify.com/embed/album/4AnAiO6p63i5cCj2t94CWu?utm_source=generator",
    keywords: "Secretary, boss, office romance, narcissism, resignation, childhood trauma, memory, comedy, love, perfectionist, vice chairman, webtoon, secrets, past, healing, relationship, growth, loyalty, humor, chemistry, childhood connection, brotherly rivalry, family secrets, lighthearted, romance.",
    keyGenre: "Romance, Comedy, Workplace, Drama, Mystery, Psychological, Webtoon Adaptation, Contemporary",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Big Mouth", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4XV2E8Aet6Qcf90zfTGuqe9Vmxip6UTGUQ&s", 
    alt: "Big Mouth Poster",
    genre: "Noir • Thriller", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "AStory",
    rating: "⭐ 4", 
    mood: "Conspiratorial",
    story: "Park Chang-ho, an unsuccessful lawyer known as 'Big Mouth' for talking a big game but achieving little, gets caught up in a murder case and is framed as the notorious genius con artist 'Big Mouse'. To survive in prison and protect his family, he must actually become the person he is accused of being while his wife, a brave nurse, fights from the outside to clear his name and expose a massive city-wide conspiracy.",
    hook: "An underperforming lawyer is framed as a notorious criminal and must become him to survive.",
    quote: "I'm not Big Mouse. But if I have to be, I will.",
    watch: "https://ww16.dramacool.bg/episode/97337/big-mouth-2022-episode-1-hd",
    trailer: "https://www.youtube.com/embed/q2bDXqjyxSk?si=OiIzFzTZi7z7vwjK",
    laugh: "https://www.youtube.com/shorts/-BGidtYw0zU",
    spotify: "https://open.spotify.com/embed/playlist/4sRdpB331r7MxKtGPh8NyK?utm_source=generator",
    keywords: "Lawyer, framed, prison, conspiracy, con artist, survival, mystery, thriller, crime, noir, identity, nurse, corruption, revenge, secret, power struggle, investigation, truth, hidden mastermind, suspense, loyalty, action, redemption, city secrets, high stakes.",
    keyGenre: "Noir, Thriller, Crime, Mystery, Law, Drama, Action, Suspense, Psychological",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "True Beauty", 
    poster: "https://m.media-amazon.com/images/M/MV5BZTFlNWFiNGQtNjA3Zi00ODNmLTgyNWQtODk4ZGQ2OWZjZjAxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "True Beauty Poster",
    genre: "Romance • Youth", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 3", 
    mood: "Transformative",
    story: "Lim Ju-kyung, a high school student bullied for her appearance, masters the art of makeup to transform herself into a 'goddess' after transferring schools. While she lives in fear of her bare face being discovered, she becomes entangled with Lee Su-ho, a handsome but cold student who knows her secret, and Han Seo-jun, a rebellious but soft-hearted boy. Together, they navigate love, friendship, and the meaning of true beauty.",
    hook: "A high school girl uses makeup to hide her insecurities and becomes a school celebrity.",
    quote: "You're pretty even without makeup.",
    watch: "https://ww16.dramacool.bg/episode/98301/true-beauty-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/5ybpUmlJnbqeo3KAv05MLI?utm_source=generator",
    keywords: "Makeup, high school, insecurities, transformation, love triangle, youth, friendship, beauty, secret, webtoon, self-esteem, popularity, rival, romance, comedy, trauma, growth, past, bromance, family, bullying, school life, celebrity, heartthrob, idol.",
    keyGenre: "Romance, Comedy, Youth, Drama, Coming of Age, School, Webtoon Adaptation, Slice of Life",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "It's Okay to Not Be Okay", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTanYyP9U2Bi7E5roySa8JdBCi5TqBbC8gvrQ&s", 
    alt: "It's Okay to Not Be Okay Poster",
    genre: "Romance • Psychological", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Story TV",
    rating: "⭐ 5", 
    mood: "Unconventional",
    story: "Moon Gang-tae, a selfless community health worker at a psychiatric ward, has spent his life caring for his autistic older brother. He crosses paths with Ko Moon-young, a famous children's book author with an antisocial personality disorder. As their lives intertwine, they begin to uncover traumatic secrets from their pasts and help each other heal their deep emotional wounds through an unconventional and intense romance.",
    hook: "A psych ward worker and an antisocial children's book writer heal each other's emotional wounds.",
    quote: "Your soul is still a child.",
    watch: "https://ww16.dramacool.bg/episode/94775/its-okay-to-not-be-okay-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/755HTtRdITPRmXkcZysj27?utm_source=generator",
    keywords: "Mental health, autism, healing, trauma, romance, fairy tales, psych ward, obsession, antisocial, family, secrets, childhood, emotions, growth, brotherly love, writer, caretaker, dark past, mystery, symbolism, gothic, psychological, redemption, self-discovery, compassion.",
    keyGenre: "Romance, Psychological, Drama, Melodrama, Mystery, Comedy, Healing, Slice of Life",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Crash Landing on You", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVNooh_B-bF0cToQvjidPf8Di2gyis6oDjxg&s", 
    alt: "Crash Landing on You Poster",
    genre: "Romance • Drama", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 3", 
    mood: "Forbidden",
    story: "Yoon Se-ri, a successful South Korean businesswoman and chaebol heiress, is swept up by a sudden tornado while paragliding and accidentally lands in the North Korean portion of the Demilitarized Zone. She is discovered by Captain Ri Jeong-hyeok, a member of the North Korean elite special forces. He decides to hide and protect her while planning a way to return her home, leading to a forbidden love across the border.",
    hook: "A South Korean heiress accidentally lands in North Korea and is protected by an army officer.",
    quote: "Sometimes the wrong train takes you to the right station.",
    watch: "https://ww16.dramacool.bg/episode/96321/crash-landing-on-you-2019-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/1lb206sGMTJryXF66FpT0k?utm_source=generator",
    keywords: "North Korea, paragliding, forbidden love, border, survival, chaebol, army, secrets, culture shock, friendship, sacrifice, adventure, tension, village life, political intrigue, loyalty, fate, star-crossed lovers, escape, family rivalry, humor, high stakes, longing, reunion, bridge.",
    keyGenre: "Romance, Drama, Comedy, Action, Political, Melodrama, Military, Business",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Vincenzo", 
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyWu9djUIjihbg1o6GTF2dhGCeTUzmlGbzNg&s", 
    alt: "Vincenzo Poster",
    genre: "Crime • Dark Comedy", 
    episodes: "▶️ 20",
    season: "⏳ 1",
    studio: "Logos Film",
    rating: "⭐ 4", 
    mood: "Brutal",
    story: "Vincenzo Cassano, a Korean-Italian lawyer and Mafia consigliere, returns to South Korea to recover hidden gold beneath a plaza. However, he finds himself caught in a legal war against a corrupt and powerful conglomerate, Babel Group. To take them down, he teams up with a sharp-tongued lawyer, Hong Cha-young, and uses his brutal Mafia tactics to give the villains a taste of their own medicine, all while becoming an unlikely hero to the plaza's quirky tenants.",
    hook: "An Italian Mafia lawyer returns to Korea to take down a corrupt conglomerate using his own dark methods.",
    quote: "Only evil can punish evil.",
    watch: "https://ww16.dramacool.bg/episode/97427/vincenzo-2021-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/5niZpLQaFlQzM4cDFz4ySk?utm_source=generator",
    keywords: "Mafia, lawyer, corruption, gold, revenge, dark comedy, action, legal battle, conglomerate, justice, consigliere, plaza, tenants, strategy, power struggle, betrayal, loyalty, anti-hero, pigeon, humor, villain, high stakes, teamwork, mystery, transformation.",
    keyGenre: "Crime, Dark Comedy, Action, Law, Thriller, Drama, Mystery, Revenge",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Branding in Seongsu", 
    poster: "https://a.ltrbxd.com/resized/film-poster/1/1/4/2/7/5/1/1142751-branding-in-seongsu-0-230-0-345-crop.jpg?v=0db6937041", 
    alt: "Seongsu Poster",
    genre: "Romance • Supernatural", 
    episodes: "▶️ 24",
    season: "⏳ 1",
    studio: "STUDIO X+U",
    rating: "⭐ 5", 
    mood: "Competitive",
    story: "Kang Na-eon, a cold and successful marketing executive who lives for work, and So Eun-ho, a carefree and charming intern, find their lives turned upside down when they accidentally swap bodies after a mysterious kiss. Forced to live each other's lives, they must navigate the high-pressure world of branding and corporate intrigue while searching for a way to return to their original bodies and discovering unexpected truths about one another.",
    hook: "A workaholic marketing leader and a laid-back intern swap bodies after an unexpected kiss.",
    quote: "You can't sell a product if you don't have a soul.",
    watch: "https://ww16.dramacool.bg/episode/92570/branding-in-seongsu-2024-episode-1-hd",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/6u1G4DJ0AoFdFe3A4TIvK6?utm_source=generator",
    keywords: "Body swap, marketing, intern, office romance, supernatural, corporate, branding, mystery, kiss, personality clash, identity, competition, project, secrets, friendship, growth, workplace, supernatural, comedy, romance, misunderstanding, teamwork, career, ambition, fashion.",
    keyGenre: "Romance, Supernatural, Comedy, Workplace, Drama, Mystery, Business, Contemporary",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Abyss", 
    poster: "https://m.media-amazon.com/images/M/MV5BNjg2M2NiNDMtYTQ0ZS00YzI0LTk0NzMtNDBmNDVkZDg2YTVkXkEyXkFqcGc@._V1_.jpg", 
    alt: "Abyss Poster",
    genre: "Fantasy • Thriller", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 2", 
    mood: "Mystical",
    story: "Go Se-yeon, a beautiful and successful prosecutor, and Cha Min, an unattractive but kind-hearted heir, are both tragically killed and then revived into completely different bodies by a supernatural orb called the 'Abyss'. The new bodies reflect the beauty of their souls, leaving Se-yeon with a plain appearance and Cha Min as a handsome young man. Together, they work to uncover the truth behind their deaths and track down a serial killer.",
    hook: "Two people are reincarnated into different bodies that reflect their souls and must find their killer.",
    quote: "The Abyss revives you in the form of your soul.",
    watch: "https://ww16.dramacool.bg/episode/77604/abyss-2019-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/0iBLdXUhMJjiF2qCuz9U5z?utm_source=generator",
    keywords: "Reincarnation, mystery, serial killer, supernatural, prosecutor, heir, identity, body change, thriller, romance, investigation, orb, death, justice, soul beauty, secrets, past, friendship, crime, suspense, detective, fate, magic, hidden identity, pursuit.",
    keyGenre: "Fantasy, Thriller, Mystery, Romance, Crime, Supernatural, Drama, Law",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Queen of the Ring", 
    poster: "https://i.pinimg.com/736x/9f/b2/c5/9fb2c5c8f5438ad414906cc0d2ea4327.jpg", 
    alt: "Queen Ring Poster",
    genre: "Fantasy • Romance", 
    episodes: "▶️ 6",
    season: "⏳ 1",
    studio: "MBC",
    rating: "⭐ 5", 
    mood: "Insecure",
    story: "Nan-hee, a girl who lacks confidence in her appearance, receives a mysterious family heirloom ring that can make her appear as the ideal woman to the person she likes. She uses the ring to win the heart of Se-gun, the most popular and handsome boy at her university who only dates beautiful women. However, as their relationship deepens, Nan-hee must face the fear of her secret being exposed and the question of whether true love can exist behind a mask.",
    hook: "A girl uses a magic ring to become the ideal type of her handsome crush.",
    quote: "True beauty is what's on the inside, or so they say.",
    watch: "https://ww16.dramacool.bg/episode/46600/three-color-fantasy-queen-of-the-ring-2017-episode-1",
    trailer: "",
    laugh: "",
    spotify: "",
    keywords: "Magic ring, beauty, insecurities, university, crush, secret identity, transformation, confidence, romance, comedy, hidden truth, popularity, appearance, family heirloom, short drama, love triangle, growth, inner beauty, illusion, dating, superficiality, self-discovery, youth.",
    keyGenre: "Fantasy, Romance, Comedy, Youth, Drama, Supernatural, Short Drama",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "18 Again", 
    poster: "https://i.pinimg.com/736x/a6/88/47/a6884717a8a52dfa080f5659f76d8da1.jpg", 
    alt: "18 Again Poster",
    genre: "Fantasy • Life", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "JTBC Studios",
    rating: "⭐ 3", 
    mood: "Reflective",
    story: "Hong Dae-young, a 37-year-old man on the verge of divorce and recently fired from his job, miraculously wakes up in his 18-year-old body while retaining his adult mind. Seeing this as a second chance, he changes his name to Go Woo-young and enrolls in his children's high school. As he befriends his own kids and reconnects with his wife under a new identity, he begins to understand the mistakes he made in the past and what truly matters in life.",
    hook: "A man on the verge of divorce gets a second chance when he transforms back into his 18-year-old self.",
    quote: "I wanted to be a good father, but I didn't know how.",
    watch: "https://ww16.dramacool.bg/episode/92659/18-again-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/06VbJ1lBH89hPr3MCToH93?utm_source=generator",
    keywords: "Time travel, second chance, family, divorce, high school, basketball, fatherhood, reconciliation, identity, youth, growth, life lessons, friendship, healing, parenting, regrets, dream, transformation, marriage, love, childhood, sports, emotional, secrets, discovery.",
    keyGenre: "Fantasy, Life, Comedy, Drama, Family, Youth, Romance, Coming of Age, Healing",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "King the Land", 
    poster: "https://m.media-amazon.com/images/M/MV5BODM2MGU3OTItNTUyZS00ODc2LWJlNzMtOTI5ZTQ4MjljMzI4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "King Land Poster",
    genre: "Romance • Comedy", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "npio Entertainment",
    rating: "⭐ 4", 
    mood: "Sparkling",
    story: "Gu Won is the cold and brilliant heir to a luxury hotel conglomerate who despises fake smiles due to a past trauma. He clashes with Cheon Sa-rang, a hardworking and cheerful hotelier known for her radiant smile, which is a requirement for her job. As they are forced to work together, their initial bickering turns into a sweet and sincere romance that helps Gu Won heal his past and Sa-rang achieve her dreams in the world of luxury hospitality.",
    hook: "A hotel heir who hates fake smiles falls for a cheerful employee whose smile is her trademark.",
    quote: "Don't smile in front of me.",
    watch: "https://ww16.dramacool.bg/episode/95998/king-the-land-2023-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/27G1vTfuXVxx1jpDJ4SUGE?utm_source=generator",
    keywords: "Hotel, heir, smile, romance, comedy, workplace, chaebol, hotelier, luxury, bickering, healing, trauma, dreams, success, friendship, love story, hospitality, employee, boss, lighthearted, chemistry, family secrets, rivalry, heartwarming, happiness.",
    keyGenre: "Romance, Comedy, Workplace, Drama, Business, Contemporary",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Queen of Tears", 
    poster: "https://i.pinimg.com/736x/0b/2e/9f/0b2e9f2a20b251450178800397c419b2.jpg", 
    alt: "Queen Tears Poster",
    genre: "Romance • Melodrama", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 4", 
    mood: "Bittersweet",
    story: "Hong Hae-in, the cold and powerful 'queen' of a department store conglomerate, and Baek Hyun-woo, her humble but successful lawyer husband, face a crisis in their three-year marriage. Just as they are on the brink of divorce, a shocking life-changing revelation forces them to confront their true feelings and fight for their love against a backdrop of corporate betrayal, family drama, and the fragile nature of life.",
    hook: "A powerful couple faces a crisis in their marriage and rediscover their love in the most unexpected way.",
    quote: "I thought I hated you, but I was just scared of losing you.",
    watch: "https://ww16.dramacool.bg/episode/97409/queen-of-tears-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/1VpYKmibzikZqeSo3HIij7?utm_source=generator",
    keywords: "Marriage crisis, terminal illness, chaebol, corporate war, divorce, reconciliation, lawyer, department store, family drama, love, tragedy, healing, secrets, betrayal, power struggle, second chance, emotional, romance, luxury, sacrifice, resilience, memory, truth, connection.",
    keyGenre: "Romance, Melodrama, Business, Drama, Family, Psychological, Tragedy",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Uncanny Counter", 
    poster: "https://m.media-amazon.com/images/I/81HWMykk35L.jpg", 
    alt: "Uncanny Counter Poster",
    genre: "Fantasy • Action", 
    episodes: "▶️ 28",
    season: "⏳ 2",
    studio: "Neo Entertainment",
    rating: "⭐ 5", 
    mood: "Heroic",
    story: "Season 1: A group of demon hunters called 'Counters' pose as employees at a noodle restaurant while using their supernatural powers to track down and banish evil spirits that prey on humans. <br><br> Season 2: The Counters face even more powerful demons and a new team of rivals, pushing their abilities to the limit as they fight to protect the balance between the human world and the afterlife.",
    hook: "Demon hunters disguise themselves as noodle shop workers to hunt down evil spirits.",
    quote: "Evil spirits are everywhere, but so are we.",
    watch: "https://ww16.dramacool.bg/episode/94791/the-uncanny-counter-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/6SxMjq1vhQt2lw1kHktMOv?utm_source=generator",
    keywords: "Demon hunting, supernatural, action, team, spirits, noodle shop, powers, afterlife, justice, friendship, courage, fantasy, villains, mystery, training, brotherhood, sacrifice, paranormal, ghosts, evil, protection, mission, heroism, growth, high stakes.",
    keyGenre: "Fantasy, Action, Supernatural, Thriller, Mystery, Drama, Comedy",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Itaewon Class", 
    poster: "https://i.pinimg.com/736x/ee/8b/6f/ee8b6f1eb5680391a54e38096514eeb6.jpg", 
    alt: "Itaewon Class Poster",
    genre: "Drama • Revenge", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Showbox",
    rating: "⭐ 1", 
    mood: "Defiant",
    story: "Park Sae-ro-yi, a determined young man with unshakeable principles, loses his father and is sent to prison due to the actions of a powerful food conglomerate's heir. After his release, he opens a pub in Itaewon with a diverse group of misfits, aiming to take down the conglomerate and achieve his 15-year revenge plan while building his own empire and staying true to his values.",
    hook: "An ex-convict and his team of misfits work to open a successful pub and take revenge on a powerful conglomerate.",
    quote: "My life is just starting. I'm going to do everything I want.",
    watch: "https://ww16.dramacool.bg/episode/91382/itaewon-class-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/2PsmLUt0LAcT2c9xzDmxI0?utm_source=generator",
    keywords: "Revenge, ambition, pub, diversity, Itaewon, success, principles, conglomerate, father, prison, team, growth, love, competition, business, loyalty, social issues, survival, dream, underdog, empowerment, determination, fashion, food industry, friendship.",
    keyGenre: "Drama, Life, Revenge, Business, Romance, Youth, Social Issues",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Gaus Electronics", 
    poster: "https://asianwiki.com/images/c/cf/Gaus_Electronics-p1.jpg", 
    alt: "Gaus Poster",
    genre: "Comedy • Workplace", 
    episodes: "▶️ 12",
    season: "⏳ 1",
    studio: "Pan Cinema",
    rating: "⭐ 5", 
    mood: "Relatable",
    story: "In the quirky marketing department of Gaus Electronics, Lee Sang-sik is a well-meaning but accident-prone employee who constantly clashes with his hot-tempered assistant manager, Cha Na-rae. Along with a chaebol heir trying to live as a commoner and other eccentric colleagues, they navigate the hilarious and relatable struggles of corporate life, office politics, and unexpected romance in this zany workplace comedy.",
    hook: "Relatable and hilarious office life struggles in a quirky marketing department.",
    quote: "Working here is like a survival game.",
    watch: "https://ww16.dramacool.bg/episode/87562/gaus-electronics-2022-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/0fQxaPTIwZkGfuI4jWob0U?utm_source=generator",
    keywords: "Office, comedy, marketing, romance, corporate life, relatable, humor, chaebol heir, internship, workplace politics, bickering, friendship, zany, satire, social pressure, technology, teamwork, eccentric characters, lighthearted, parody, career, love, daily life, funny, department.",
    keyGenre: "Comedy, Workplace, Slice of Life, Romance, Drama, Business",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Mr. Queen", 
    poster: "https://m.media-amazon.com/images/M/MV5BMmMzZDdjMjktMjY0MS00ODk2LTgxZmEtZTlkYmI0YTQ3MzQ5XkEyXkFqcGc@._V1_.jpg", 
    alt: "Mr. Queen Poster",
    genre: "Fantasy • Comedy", 
    episodes: "▶️ 20",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 5", 
    mood: "Hysterical",
    story: "Jang Bong-hwan, a modern-day playboy chef working at the Blue House, finds himself trapped in the body of Queen Kim So-yong during the Joseon era after a mysterious accident. Forced to navigate the dangerous and complex world of the royal palace, he must deal with a King who hides a secret, power-hungry court officials, and his own identity crisis while using his culinary skills to survive and unintentionally changing history.",
    hook: "A modern-day male chef wakes up in the body of a Queen in the Joseon era.",
    quote: "I'm a man! A real man from the future!",
    watch: "https://ww16.dramacool.bg/episode/94724/mr-queen-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/1bRi5462HKgud7bhFhYnjZ?utm_source=generator",
    keywords: "Time travel, body swap, Joseon era, comedy, chef, palace intrigue, queen, king, culinary, historical, gender bender, power struggle, romance, humor, secret, identity, mystery, politics, survival, food, funny, modern vs traditional, friendship, transformation, royalty.",
    keyGenre: "Fantasy, Comedy, Historical, Romance, Political, Drama, Supernatural",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Strong Girl Nam-soon", 
    poster: "https://m.media-amazon.com/images/M/MV5BNjdiOTVmNTMtNGQ3ZS00MDc5LTg1NGEtMGFjYTIzZTdjMDY5XkEyXkFqcGc@._V1_.jpg", 
    alt: "Nam-soon Poster",
    genre: "Action • Comedy", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Barunson C&C",
    rating: "⭐ 3", 
    mood: "Playful",
    story: "Kang Nam-soon, who went missing as a child in Mongolia, returns to South Korea to find her biological family. She reunites with her mother and grandmother, who also possess superhuman strength. The three generations of women become entangled in a massive drug case in Gangnam and team up with a young detective to take down a dangerous crime syndicate, using their incredible powers for justice.",
    hook: "Three generations of women with superhuman strength fight drug crimes in Gangnam.",
    quote: "Don't mess with the women in this family.",
    watch: "https://ww16.myasiantv.es/ep/strong-girl-namsoon-2023-episode-1-english-subbed/",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/4S28HIpDJ7yz3wkG5q1Ro2?utm_source=generator",
    keywords: "Superpowers, strength, family, action, comedy, drugs, Gangnam, detective, crime syndicate, investigation, mystery, heroism, reunion, mother-daughter, grandma, romance, justice, spin-off, humor, villain, danger, protection, social issues, power, teamwork.",
    keyGenre: "Action, Comedy, Supernatural, Crime, Thriller, Mystery, Drama, Romance",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Lovely Runner", 
    poster: "https://media.themoviedb.org/t/p/w220_and_h330_face/5xlNin5YXDrm4ZwHZMpp4TKdxFY.jpg", 
    alt: "Lovely Runner Poster",
    genre: "Romance • Fantasy", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Bon Factory",
    rating: "⭐ 4", 
    mood: "Devoted",
    story: "Im Sol is a devoted fan of top star Ryu Sun-jae, whose music helped her find hope after an accident left her paralyzed. When news breaks of Sun-jae's tragic death, Sol is miraculously transported 15 years into the past, to their high school days. Seeing this as a chance from heaven, she vows to change the course of destiny and save Sun-jae's life, all while discovering that their connection goes deeper than she ever imagined.",
    hook: "A devoted fan travels back in time to save her favorite star from a tragic fate.",
    quote: "I'll protect you this time.",
    watch: "https://ww16.dramacool.bg/episode/98839/lovely-runner-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/0L3w221QtLgtyoQlpR7skW?utm_source=generator",
    keywords: "Time travel, fan, idol, high school, protection, destiny, first love, tragedy, hope, music, saving life, secrets, friendship, romance, comedy, fate, star-crossed, past, future, disability, healing, youth, determination, mysterious connection, second chance.",
    keyGenre: "Romance, Fantasy, Youth, Drama, Comedy, Time Travel, Mystery, Music, Healing",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
{ 
    name: "20th Century Girl", 
    poster: "https://m.media-amazon.com/images/M/MV5BMjA4NzYxNWItZWJmNi00ODE2LTgwZDgtMzBkN2MzOGZhNDEzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "20th Century Girl Poster",
    genre: "Romance • Youth", 
    episodes: "▶️ Movie",
    studio: "Yong Film",
    rating: "⭐ 5", 
    mood: "Nostalgic",
    story: "In 1999, a seventeen-year-old girl with a heart of gold starts keeping close tabs on a popular classmate to help her smitten best friend — only to get swept up in her own bittersweet first love story.",
    hook: "A teenage girl monitors her friend's crush, but finds herself falling for his best friend instead.",
    quote: "I'll be your eyes and ears. Tell me everything you want to know about him.",
    watch: "https://www.dailymotion.com/video/x8h2gp7",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/playlist/0gVSGtuJTHGx4XWdlPKKe7?utm_source=generator",
    keywords: "First love, 1999, nostalgia, friendship, high school, heart surgery, letter, mistake identity, broadcasting club, bittersweet, coming of age, 20th century, rainy days, video store.",
    keyGenre: "Romance, Youth, Drama, Melodrama, Friendship",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Tale of the Nine-Tailed", 
    poster: "https://m.media-amazon.com/images/M/MV5BMjQ5NzE5ZjUtZDVlYi00NjNlLWE0OTAtZTllNWYxZDMzNjFkXkEyXkFqcGc@._V1_.jpg", 
    alt: "Nine-Tailed Poster",
    genre: "Fantasy • Action", 
    episodes: "▶️ 28",
    season: "⏳ 2",
    studio: "Studio Dragon",
    rating: "⭐ 1", 
    mood: "Mythical",
    story: "Season 1: Lee Yeon, a legendary nine-tailed fox who was once a mountain god, lives in the modern world hunting down supernatural beings while searching for the reincarnation of his lost love. <br><br> Season 2: Lee Yeon is unexpectedly transported back to 1938, a time of turmoil, where he encounters familiar faces and new enemies, forcing him to fight his way back to the present and his loved ones.",
    hook: "A legendary nine-tailed fox lives in the human world while waiting for his first love to be reborn.",
    quote: "I've been waiting for you for centuries.",
    watch: "https://ww16.dramacool.bg/episode/89886/tale-of-the-nine-tailed-2020-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/5bPUFq5CAtNGj5LKKpY1aH?utm_source=generator",
    keywords: "Nine-tailed fox, gumiho, reincarnation, supernatural, action, myth, folklore, romance, brothers, duty, destiny, lost love, urban fantasy, time travel, historical, mystery, spirits, battle, fate, longing, protection, sacrifice, legend, demon hunting, mountain god.",
    keyGenre: "Fantasy, Action, Romance, Supernatural, Thriller, Historical, Mystery, Drama",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Alchemy of Souls", 
    poster: "https://image.tmdb.org/t/p/original/q2IiPRSXPOZ6qVRj36WRAYEQyHs.jpg", 
    alt: "Alchemy Souls Poster",
    genre: "Fantasy • Romance", 
    episodes: "▶️ 30",
    season: "⏳ 2",
    studio: "Studio Dragon",
    rating: "⭐ 5", 
    mood: "Epic",
    story: "Season 1: In the fictional nation of Daeho, a powerful assassin named Naksu soul-switches with a blind girl and becomes the servant and secret teacher to a nobleman's son, Jang Uk, helping him unlock his sealed magic. <br><br> Season 2: Three years after a tragic ending, Jang Uk has become a powerful but cold mage who captures soul shifters. He encounters a mysterious woman who looks like Naksu but has lost her memories, leading to a new and dangerous connection.",
    hook: "A powerful assassin's soul is trapped in a weak body, leading her to become a teacher to a nobleman.",
    quote: "Our fate was twisted from the very beginning.",
    watch: "https://ww16.dramacool.bg/episode/98147/alchemy-of-souls-2022-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/6vD8YD5TPXuOdhRjz91iGI?utm_source=generator",
    keywords: "Soul switch, magic, mages, assassin, romance, fantasy world, martial arts, teacher, pupil, destiny, tragedy, power, secrets, betrayal, rebirth, alchemy, spirits, ancient, battle, fate, identity, loyalty, mystery, epic, star-crossed.",
    keyGenre: "Fantasy, Romance, Action, Period Drama, Mystery, Supernatural, Adventure",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Strong Woman Do Bong-soon", 
    poster: "https://m.media-amazon.com/images/M/MV5BZTliMWVjYmYtNmQ2My00Y2UxLWJiZjQtNTg1OTk0OGE0M2IzXkEyXkFqcGc@._V1_.jpg", 
    alt: "Bong-soon Poster",
    genre: "Romance • Comedy", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "JS Pictures",
    rating: "⭐ 4", 
    mood: "Whimsical",
    story: "Do Bong-soon was born with superhuman strength, a secret passed down through the women in her family. She dreams of being a refined woman and becoming a game designer. Her incredible power catches the attention of Min-hyuk, the eccentric CEO of a gaming company, who hires her as his bodyguard. While navigating a blossoming romance with her boss and her longtime crush on a detective, Bong-soon must use her strength to stop a serial kidnapper in her neighborhood.",
    hook: "A tiny girl with superhuman strength is hired as a bodyguard for a gaming company CEO.",
    quote: "My power is a gift, not a curse.",
    watch: "https://ww16.dramacool.bg/episode/96204/strong-woman-do-bong-soon-2017-episode-1-hd",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/playlist/3nzTlIyULgmFHJw3AqRTo5?utm_source=generator",
    keywords: "Super strength, bodyguard, CEO, romance, comedy, kidnapping, mystery, game design, secret, love triangle, humor, action, protection, female lead, justice, neighborhood, kidnapping, strength, cute, bickering, investigation, supernatural, family, hero, funny.",
    keyGenre: "Romance, Comedy, Supernatural, Action, Thriller, Mystery, Drama, Crime",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Doctor Slump", 
    poster: "https://m.media-amazon.com/images/M/MV5BZWZhMjI4MzYtYjY2Mi00ZmNkLWFkYjMtZjc3NzRiZDg2NjA0XkEyXkFqcGc@._V1_.jpg", 
    alt: "Doctor Slump Poster",
    genre: "Romance • Medical", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "SLL",
    rating: "⭐ 4", 
    mood: "Comforting",
    story: "Yeo Jeong-woo and Nam Ha-neul were high school rivals who both became successful doctors. However, they both hit the lowest point of their lives simultaneously—Jeong-woo due to a mysterious medical malpractice case and Ha-neul due to severe burnout and depression. They cross paths again during their 'slump' while living as neighbors and begin to find comfort, healing, and love in each other as they try to reclaim their lives.",
    hook: "Two rival doctors who hit rock bottom reunite and find comfort in each other.",
    quote: "It's okay to fall. What matters is that we have someone to help us up.",
    watch: "https://ww16.dramacool.bg/episode/96044/doctor-slump-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/1VvNlrYT750NlpdfJerQRV?utm_source=generator",
    keywords: "Medical, rivals to lovers, healing, depression, burnout, slump, reunion, neighbors, mystery, success, failure, comfort, romance, comedy, life lessons, doctors, past, friendship, growth, hospital, support, mental health, truth, school, rebuilding.",
    keyGenre: "Romance, Medical, Comedy, Drama, Healing, Slice of Life, Mystery, Psychological",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Weightlifting Fairy Kim Bok-joo", 
    poster: "https://image.tmdb.org/t/p/original/oARcy8kubYekRqii04obOlvw442.jpg", 
    alt: "Weightlifting Poster",
    genre: "Romance • Youth", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Chorokbaem Media",
    rating: "⭐ 2", 
    mood: "Youthful",
    story: "Kim Bok-joo is a naturally gifted weightlifter at a sports university who focuses only on her sport. Her life takes an unexpected turn when she experiences her first love, a doctor who happens to be the brother of her childhood friend, a talented swimmer named Jung Joon-hyung. As she navigates the challenges of being a female athlete, body image, and university life, she finds herself falling for Joon-hyung in a sweet and supportive coming-of-age romance.",
    hook: "A weightlifter at a sports university finds her first love and her true self.",
    quote: "Do you like Messi?",
    watch: "https://ww16.dramacool.bg/episode/91893/weightlifting-fairy-kim-bok-joo-2016-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/1nDbldlkvfgg9QxqtA3vtL?utm_source=generator",
    keywords: "Weightlifting, swimming, university, youth, first love, athlete, sports, coming of age, body image, friendship, romance, comedy, bickering, support, dreams, sweet, health, childhood friends, family, campus life, training, growth, competition, lighthearted, relatable.",
    keyGenre: "Romance, Youth, Comedy, Sports, Slice of Life, Coming of Age, Drama",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "A Shop for Killers", 
    poster: "https://image.tmdb.org/t/p/original/7yUY1HUyQuybbvkAAhLzQ7x1l9g.jpg", 
    alt: "Shop Killers Poster",
    genre: "Action • Mystery", 
    episodes: "▶️ 8",
    season: "⏳ 1",
    studio: "Merry Christmas",
    rating: "⭐ 5", 
    mood: "Suspenseful",
    story: "After the sudden and suspicious death of her uncle, college student Jung Ji-an discovers that he ran a secret and highly dangerous online mall for killers. She becomes the target of lethal assassins who want to seize the shop and its secrets. To survive, she must rely on the survival training her uncle gave her throughout her childhood and uncover the truth about his mysterious past and the hidden world he left behind.",
    hook: "A girl inherits a secret shopping mall for killers and must fight to survive when she becomes a target.",
    quote: "Listen carefully, Ji-an. Everything I taught you was for this moment.",
    watch: "https://ww16.dramacool.bg/episode/96153/a-shop-for-killers-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/7JVn5g3x2IL8awXneTq2zK?utm_source=generator",
    keywords: "Assassins, shopping mall, mystery, survival, uncle, training, action, secrets, legacy, danger, weapons, investigation, childhood, dark past, suspense, sniper, target, strategy, lethal, underground, betrayal, loyalty, protection, identity, high stakes.",
    keyGenre: "Action, Mystery, Thriller, Suspense, Crime, Drama",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "The Frog", 
    poster: "https://m.media-amazon.com/images/M/MV5BZGM4Y2VhYjMtZGMzYS00YTI5LTk5NWUtMTcxNTJlOGMyZGE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
    alt: "The Frog Poster",
    genre: "Thriller • Mystery", 
    episodes: "▶️ 8",
    season: "⏳ 1",
    studio: "Studio Flow",
    rating: "⭐ 5", 
    mood: "Unsettling",
    story: "Two men, living in different time periods but connected by the same vacation home, find their peaceful lives shattered by the arrival of mysterious and dangerous guests. In the present, a pension owner's life begins to crumble after a strange woman visits, while in the past, a motel owner faces a similar nightmare. As their stories intertwine, a retired detective works to uncover the dark truth behind the recurring tragedies.",
    hook: "A mysterious guest's arrival shatters the peaceful lives of two different property owners across time.",
    quote: "The guest who wasn't supposed to come has arrived.",
    watch: "https://ww16.dramacool.bg/episode/56579/the-frog-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/playlist/4xnLgsRPdhSHeRMuj7S5Gj?utm_source=generator",
    keywords: "Pension, motel, mysterious guest, time periods, thriller, mystery, dark secrets, crime, investigation, suspense, tragedy, past vs present, consequences, survival, identity, detective, psychological, vacation house, hidden truth, unsettling, atmosphere, manipulation, fear, obsession.",
    keyGenre: "Thriller, Mystery, Suspense, Psychological, Crime, Drama",
    home: true, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "No Gain, No Love", 
    poster: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p27977261_b_v13_ac.jpg", 
    alt: "No Gain Poster",
    genre: "Romance • Comedy", 
    episodes: "▶️ 12",
    season: "⏳ 1",
    studio: "CJ ENM",
    rating: "⭐ 3", 
    mood: "Calculated",
    story: "Son Hae-yeong is a woman who hates losing money and calculated everything in her life to avoid any loss. To secure a promotion at her company, which only considers married employees for the role, she plans a fake wedding. She recruits Kim Ji-uk, a kind and selfless convenience store worker who can't stand seeing anyone in need, to be her fake groom. Their contract relationship leads to unexpected feelings and a comedic clash of values.",
    hook: "A calculated woman and a selfless man enter a fake marriage for a promotion.",
    quote: "I'm doing this for the profit, not for love.",
    watch: "https://ww16.dramacool.bg/episode/94115/no-gain-no-love-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/00mOGaSG3cFXkhA84mycc7?utm_source=generator",
    keywords: "Fake marriage, promotion, office, profit, convenience store, romance, calculated, contract relationship, workplace, social pressure, wedding, comedy, selfishness vs altruism, career, humor, misunderstandings, fake dating, corporate culture, chemistry, love, growth, daily life, money, gain.",
    keyGenre: "Romance, Comedy, Workplace, Drama, Business, Contemporary",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  },
  { 
    name: "Love Next Door", 
    poster: "https://image.tmdb.org/t/p/original/Lfj7Cl2Ek2xJ1dFsbcl5MCitzE.jpg", 
    alt: "Love Door Poster",
    genre: "Romance • Life", 
    episodes: "▶️ 16",
    season: "⏳ 1",
    studio: "Studio Dragon",
    rating: "⭐ 3", 
    mood: "Heartwarming",
    story: "Bae Seok-ryu, a successful woman who lived a perfect life abroad, suddenly returns to her hometown to 'reboot' her life after a series of failures. She reunites with her childhood friend Choi Seung-hyo, now a prominent architect, whose mother is best friends with her own. As they face the ghosts of their past and the challenges of their present, they begin to see each other in a new light, leading to a heartwarming and nostalgic romance.",
    hook: "Childhood friends reunite as adults to face life's challenges and old feelings.",
    quote: "You're the person who knows my most embarrassing moments.",
    watch: "https://ww16.dramacool.bg/episode/98070/love-next-door-2024-episode-1",
    trailer: "",
    laugh: "",
    spotify: "https://open.spotify.com/embed/album/7km17adXavXTUiiEpm0m7u?utm_source=generator",
    keywords: "Childhood friends, family, neighbors, second chance, architect, healing, mom's friend's son, career crisis, reunion, neighborhood romance, nostalgia, growth, small town vibes, friendship, bickering, first love, life reboot, community, heartwarming, past, secrets, transformation.",
    keyGenre: "Romance, Life, Comedy, Drama, Slice of Life, Healing, Family, Coming of Age",
    home: false, trending: false, best: false, gold: false, silver: false, bronze: false
  }
];

window.kdramas = kdramas;
